// src/components/ui/Button.tsx
import React from 'react';
import { cn } from '@/lib/utils';

type Variant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'warning' | 'outline';
type Size = 'sm' | 'md' | 'lg';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

const variantClasses: Record<Variant, string> = {
  primary: 'bg-bank-600 text-white hover:bg-bank-700 active:bg-bank-800 shadow-sm',
  secondary: 'bg-bank-100 text-bank-700 hover:bg-bank-200 active:bg-bank-300',
  ghost: 'bg-transparent text-slate-600 hover:bg-slate-100 active:bg-slate-200',
  danger: 'bg-red-600 text-white hover:bg-red-700 active:bg-red-800 shadow-sm',
  warning: 'bg-amber-500 text-white hover:bg-amber-600 active:bg-amber-700 shadow-sm',
  outline: 'bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 active:bg-slate-100',
};

const sizeClasses: Record<Size, string> = {
  sm: 'h-8 px-3 text-xs gap-1.5',
  md: 'h-9 px-4 text-sm gap-1.5',
  lg: 'h-11 px-6 text-base gap-2',
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  leftIcon,
  rightIcon,
  className,
  children,
  ...rest
}) => (
  <button
    className={cn(
      'inline-flex items-center justify-center rounded-md font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed',
      variantClasses[variant],
      sizeClasses[size],
      className,
    )}
    {...rest}
  >
    {leftIcon}
    {children}
    {rightIcon}
  </button>
);

// src/lib/components/common/Button.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'outline' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let disabled = false;
  export let loading = false;
  export let fullWidth = false;
</script>

<button
  class="btn btn-{variant} btn-{size}"
  class:btn-full-width={fullWidth}
  class:btn-disabled={disabled || loading}
  disabled={disabled || loading}
  on:click
>
  {#if loading}
    <span class="spinner"></span>
  {/if}
  <slot />
</button>

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    font-weight: 500;
    border-radius: 0.5rem;
    transition: all 0.2s;
    cursor: pointer;
    border: 2px solid transparent;
  }

  .btn-sm {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
  }

  .btn-md {
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
  }

  .btn-lg {
    padding: 1rem 2rem;
    font-size: 1.125rem;
  }

  .btn-primary {
    background-color: #F59E0B;
    color: white;
    box-shadow: 0 2px 4px rgba(245, 158, 11, 0.3);
  }

  .btn-primary:hover:not(.btn-disabled) {
    background-color: #D97706;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(245, 158, 11, 0.4);
  }

  .btn-secondary {
    background-color: #92400E;
    color: white;
    box-shadow: 0 2px 4px rgba(146, 64, 14, 0.3);
  }

  .btn-secondary:hover:not(.btn-disabled) {
    background-color: #78350F;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(146, 64, 14, 0.4);
  }

  .btn-success {
    background-color: #10B981;
    color: white;
    box-shadow: 0 2px 4px rgba(16, 185, 129, 0.3);
  }

  .btn-success:hover:not(.btn-disabled) {
    background-color: #059669;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(16, 185, 129, 0.4);
  }

  .btn-danger {
    background-color: #EF4444;
    color: white;
    box-shadow: 0 2px 4px rgba(239, 68, 68, 0.3);
  }

  .btn-danger:hover:not(.btn-disabled) {
    background-color: #DC2626;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(239, 68, 68, 0.4);
  }

  .btn-outline {
    background-color: transparent;
    color: #92400E;
    border-color: #92400E;
  }

  .btn-outline:hover:not(.btn-disabled) {
    background-color: #FEF3C7;
    transform: translateY(-1px);
  }

  .btn-disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none !important;
  }

  .btn-full-width {
    width: 100%;
  }

  .spinner {
    width: 1rem;
    height: 1rem;
    border: 2px solid transparent;
    border-top-color: currentColor;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>
