// src/components/common/Button.tsx
import { forwardRef } from "react";
import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

type ButtonVariant = "primary" | "secondary" | "success" | "danger" | "ghost" | "outline";
type ButtonSize = "sm" | "md" | "lg";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  children: React.ReactNode;
}

const variantStyles: Record<ButtonVariant, string> = {
  primary: "bg-primary text-white hover:bg-primary/90 shadow-sm hover:shadow-md",
  secondary: "bg-secondary text-white hover:bg-secondary/90 shadow-sm hover:shadow-md",
  success: "bg-success text-white hover:bg-success/90 shadow-sm hover:shadow-md",
  danger: "bg-danger text-white hover:bg-danger/90 shadow-sm hover:shadow-md",
  ghost: "text-slate-600 hover:bg-slate-100 hover:text-slate-800",
  outline: "border border-slate-300 text-slate-700 bg-white hover:border-slate-400 hover:bg-slate-50",
};

const sizeStyles: Record<ButtonSize, string> = {
  sm: "px-3 py-1.5 text-sm gap-1.5",
  md: "px-4 py-2 text-sm gap-2",
  lg: "px-6 py-2.5 text-base gap-2.5",
};

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = "primary", size = "md", loading = false, disabled, className, children, ...props }, ref) => {
    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={cn(
          "inline-flex items-center justify-center font-medium rounded-lg transition-all duration-200",
          "focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary/50",
          "disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:shadow-none",
          variantStyles[variant],
          sizeStyles[size],
          className
        )}
        {...props}
      >
        {loading && <Loader2 className="w-4 h-4 animate-spin" />}
        {children}
      </button>
    );
  }
);

Button.displayName = "Button";

export default Button;

// src/lib/components/common/Button.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'outline' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let disabled = false;
  export let loading = false;
  export let fullWidth = false;
</script>

<button
  class="btn btn-{variant} btn-{size}"
  class:btn-full-width={fullWidth}
  class:btn-disabled={disabled || loading}
  disabled={disabled || loading}
  on:click
>
  {#if loading}
    <span class="spinner"></span>
  {/if}
  <slot />
</button>

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    font-weight: 500;
    border-radius: 0.5rem;
    transition: all 0.2s;
    cursor: pointer;
    border: 2px solid transparent;
  }

  .btn-sm {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
  }

  .btn-md {
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
  }

  .btn-lg {
    padding: 1rem 2rem;
    font-size: 1.125rem;
  }

  .btn-primary {
    background-color: #F59E0B;
    color: white;
    box-shadow: 0 2px 4px rgba(245, 158, 11, 0.3);
  }

  .btn-primary:hover:not(.btn-disabled) {
    background-color: #D97706;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(245, 158, 11, 0.4);
  }

  .btn-secondary {
    background-color: #92400E;
    color: white;
    box-shadow: 0 2px 4px rgba(146, 64, 14, 0.3);
  }

  .btn-secondary:hover:not(.btn-disabled) {
    background-color: #78350F;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(146, 64, 14, 0.4);
  }

  .btn-success {
    background-color: #10B981;
    color: white;
    box-shadow: 0 2px 4px rgba(16, 185, 129, 0.3);
  }

  .btn-success:hover:not(.btn-disabled) {
    background-color: #059669;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(16, 185, 129, 0.4);
  }

  .btn-danger {
    background-color: #EF4444;
    color: white;
    box-shadow: 0 2px 4px rgba(239, 68, 68, 0.3);
  }

  .btn-danger:hover:not(.btn-disabled) {
    background-color: #DC2626;
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(239, 68, 68, 0.4);
  }

  .btn-outline {
    background-color: transparent;
    color: #92400E;
    border-color: #92400E;
  }

  .btn-outline:hover:not(.btn-disabled) {
    background-color: #FEF3C7;
    transform: translateY(-1px);
  }

  .btn-disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none !important;
  }

  .btn-full-width {
    width: 100%;
  }

  .spinner {
    width: 1rem;
    height: 1rem;
    border: 2px solid transparent;
    border-top-color: currentColor;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>
