// src/lib/components/StatCard.svelte
<script lang="ts">
	import type { Component } from 'svelte';

	let {
		icon,
		title,
		value,
		color = 'teal'
	}: {
		icon: Component;
		title: string;
		value: number | string;
		color?: 'teal' | 'amber' | 'blue' | 'rose';
	} = $props();

	const colorGradients: Record<string, string> = {
		teal: 'from-teal-600 to-teal-700',
		amber: 'from-amber-500 to-amber-600',
		blue: 'from-blue-500 to-blue-600',
		rose: 'from-rose-500 to-rose-600'
	};

	const colorBgLight: Record<string, string> = {
		teal: 'bg-teal-50',
		amber: 'bg-amber-50',
		blue: 'bg-blue-50',
		rose: 'bg-rose-50'
	};

	const colorText: Record<string, string> = {
		teal: 'text-teal-700',
		amber: 'text-amber-600',
		blue: 'text-blue-600',
		rose: 'text-rose-600'
	};
</script>

<div
	class="group relative overflow-hidden rounded-2xl bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
>
	<div
		class="absolute inset-x-0 top-0 h-1 bg-gradient-to-r {colorGradients[color]}"
	></div>

	<div class="flex items-start justify-between">
		<div>
			<p class="text-sm font-medium text-gray-500">{title}</p>
			<p
				class="mt-2 text-3xl font-bold text-gray-800 transition-transform duration-300 group-hover:scale-105"
			>
				{value}
			</p>
		</div>

		<div
			class="flex h-12 w-12 items-center justify-center rounded-xl {colorBgLight[color]} transition-all duration-300 group-hover:scale-110 group-hover:rotate-3"
		>
			<svelte:component this={icon} size={24} class={colorText[color]} />
		</div>
	</div>

	<div
		class="absolute -bottom-10 -right-10 h-32 w-32 rounded-full opacity-0 transition-opacity duration-300 group-hover:opacity-10 {colorBgLight[color]}"
	></div>
</div>

// brewery-qc-system/src/components/ui/StatCard.tsx
import { motion } from 'framer-motion';
import type { ReactNode } from 'react';

interface StatCardProps {
  title: string;
  value: number | string;
  icon: ReactNode;
  trend?: 'up' | 'down' | 'neutral';
  trendValue?: string;
  color?: 'amber' | 'green' | 'orange' | 'blue' | 'red';
  delay?: number;
}

export function StatCard({ title, value, icon, trend, trendValue, color = 'amber', delay = 0 }: StatCardProps) {
  const colorClasses = {
    amber: 'from-amber-50 to-amber-100 text-amber-900',
    green: 'from-hop-50 to-green-100 text-hop-green',
    orange: 'from-warning-50 to-orange-100 text-warning-orange',
    blue: 'from-info-50 to-blue-100 text-info-blue',
    red: 'from-red-50 to-red-100 text-red-600',
  };

  const iconBgColors = {
    amber: 'bg-amber-900',
    green: 'bg-hop-green',
    orange: 'bg-warning-orange',
    blue: 'bg-info-blue',
    red: 'bg-red-600',
  };

  const trendColors = {
    up: 'text-hop-green',
    down: 'text-red-600',
    neutral: 'text-neutral-600',
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay }}
      className={`bg-gradient-to-br ${colorClasses[color]} p-5 rounded-xl shadow-sm`}
    >
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm font-medium text-neutral-600 mb-1">{title}</p>
          <motion.p
            className="text-3xl font-bold"
            initial={{ scale: 0.5 }}
            animate={{ scale: 1 }}
            transition={{ duration: 0.3, delay: delay + 0.2 }}
          >
            {value}
          </motion.p>
          {trend && trendValue && (
            <p className={`text-sm mt-2 ${trendColors[trend]}`}>
              {trend === 'up' && '↑ '}
              {trend === 'down' && '↓ '}
              {trendValue}
            </p>
          )}
        </div>
        <div className={`${iconBgColors[color]} p-3 rounded-lg text-white shadow-md`}>
          {icon}
        </div>
      </div>
    </motion.div>
  );
}
