// components/FilterBar.tsx
import { useState } from 'react';
import { PracticeStatus, ReviewStatus, Role } from '../types';
import { instruments } from '../data/mockData';

interface FilterBarProps {
  role: Role;
  onFilterChange: (filters: {
    studentName?: string;
    instrument?: string;
    status?: PracticeStatus | ReviewStatus;
  }) => void;
}

const practiceStatuses: PracticeStatus[] = ['待处理', '已确认', '已退回', '已完成'];
const reviewStatuses: ReviewStatus[] = ['待点评', '已点评', '待确认', '已完成'];

export function FilterBar({ role, onFilterChange }: FilterBarProps) {
  const [studentName, setStudentName] = useState('');
  const [instrument, setInstrument] = useState('全部');
  const [status, setStatus] = useState<PracticeStatus | ReviewStatus | ''>('');

  const handleSubmit = () => {
    onFilterChange({
      studentName: studentName || undefined,
      instrument: instrument === '全部' ? undefined : instrument,
      status: status || undefined,
    });
  };

  const handleReset = () => {
    setStudentName('');
    setInstrument('全部');
    setStatus('');
    onFilterChange({});
  };

  const statuses = role === '教务老师' ? [...practiceStatuses, ...reviewStatuses] :
                  role === '任课老师' ? [...practiceStatuses, ...reviewStatuses] :
                  reviewStatuses;

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-4">
      <div className="flex items-center gap-4">
        <div className="flex-1">
          <label className="block text-sm font-medium text-gray-700 mb-1">学生姓名</label>
          <input
            type="text"
            value={studentName}
            onChange={(e) => setStudentName(e.target.value)}
            placeholder="请输入学生姓名"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
          />
        </div>
        <div className="w-40">
          <label className="block text-sm font-medium text-gray-700 mb-1">乐器类型</label>
          <select
            value={instrument}
            onChange={(e) => setInstrument(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
          >
            {instruments.map((item) => (
              <option key={item} value={item}>{item}</option>
            ))}
          </select>
        </div>
        <div className="w-36">
          <label className="block text-sm font-medium text-gray-700 mb-1">状态</label>
          <select
            value={status}
            onChange={(e) => setStatus(e.target.value as PracticeStatus | ReviewStatus | '')}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
          >
            <option value="">全部</option>
            {statuses.map((item) => (
              <option key={item} value={item}>{item}</option>
            ))}
          </select>
        </div>
        <div className="flex items-end gap-2">
          <button
            onClick={handleSubmit}
            className="px-4 py-2 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-colors"
          >
            筛选
          </button>
          <button
            onClick={handleReset}
            className="px-4 py-2 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded-lg transition-colors"
          >
            重置
          </button>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/FilterBar.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { ReplacementFilters, ReplacementStatus } from '../types'
import { STATUS_LABEL } from '../types/enums'

interface Props {
  filters: ReplacementFilters
  placeholder?: string
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '搜索关键词',
})

const emit = defineEmits<{
  'update:filters': [filters: ReplacementFilters]
  search: []
}>()

const localKeyword = ref(props.filters.keyword || '')
const localStatus = ref<ReplacementStatus | ''>(props.filters.status || '')
const localStartDate = ref(props.filters.dateRange?.start || '')
const localEndDate = ref(props.filters.dateRange?.end || '')

watch(
  () => props.filters,
  (newFilters) => {
    localKeyword.value = newFilters.keyword || ''
    localStatus.value = newFilters.status || ''
    localStartDate.value = newFilters.dateRange?.start || ''
    localEndDate.value = newFilters.dateRange?.end || ''
  }
)

function emitFilters() {
  const filters: ReplacementFilters = {}
  if (localKeyword.value) filters.keyword = localKeyword.value
  if (localStatus.value) filters.status = localStatus.value
  if (localStartDate.value || localEndDate.value) {
    filters.dateRange = {
      start: localStartDate.value,
      end: localEndDate.value,
    }
  }
  emit('update:filters', filters)
}

function handleReset() {
  localKeyword.value = ''
  localStatus.value = ''
  localStartDate.value = ''
  localEndDate.value = ''
  emit('update:filters', {})
  emit('search')
}

function handleSearch() {
  emitFilters()
  emit('search')
}
</script>

<template>
  <div class="flex flex-wrap items-center gap-3 p-4 bg-gray-50 border border-gray-200">
    <input
      v-model="localKeyword"
      type="text"
      :placeholder="props.placeholder"
      class="px-3 py-2 text-sm border border-gray-300 bg-white w-64 focus:outline-none focus:border-blue-500"
      @keyup.enter="handleSearch"
    />

    <select
      v-model="localStatus"
      class="px-3 py-2 text-sm border border-gray-300 bg-white focus:outline-none focus:border-blue-500"
    >
      <option value="">全部状态</option>
      <option
        v-for="(label, value) in STATUS_LABEL"
        :key="value"
        :value="value"
      >
        {{ label }}
      </option>
    </select>

    <div class="flex items-center gap-2">
      <input
        v-model="localStartDate"
        type="date"
        class="px-3 py-2 text-sm border border-gray-300 bg-white focus:outline-none focus:border-blue-500"
      />
      <span class="text-gray-500 text-sm">至</span>
      <input
        v-model="localEndDate"
        type="date"
        class="px-3 py-2 text-sm border border-gray-300 bg-white focus:outline-none focus:border-blue-500"
      />
    </div>

    <div class="flex items-center gap-2 ml-auto">
      <button
        type="button"
        class="px-4 py-2 text-sm border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 transition-colors"
        @click="handleReset"
      >
        重置
      </button>
      <button
        type="button"
        class="px-4 py-2 text-sm bg-blue-900 text-white hover:bg-blue-800 transition-colors"
        @click="handleSearch"
      >
        搜索
      </button>
    </div>
  </div>
</template>
