// src/lib/components/layout/Header.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { notifications, unreadCount } from '$lib/stores/notifications';
  import NotificationPanel from '$lib/components/common/NotificationPanel.svelte';
  import NotificationBanner from '$lib/components/common/NotificationBanner.svelte';
  
  let showNotifications = false;
  let showBanner = true;
  
  function toggleNotifications() {
    showNotifications = !showNotifications;
  }
</script>

<header class="header">
  <NotificationBanner visible={showBanner} />
  <div class="header-content">
    <div class="header-brand">
      <span class="header-logo">🌾</span>
      <h1 class="header-title">农家乐经营管理系统</h1>
    </div>
    <div class="header-actions">
      <button class="header-notification" on:click={toggleNotifications}>
        <span class="notification-icon">🔔</span>
        {#if $unreadCount > 0}
          <span class="notification-count">{ $unreadCount }</span>
        {/if}
      </button>
      <NotificationPanel show={showNotifications} />
    </div>
  </div>
</header>

<style>
  .header {
    background-color: #92400E;
    color: white;
    padding: 1rem 2rem;
    box-shadow: 0 2px 8px rgba(146, 64, 14, 0.3);
    position: sticky;
    top: 0;
    z-index: 100;
  }

  .header-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
    max-width: 1400px;
    margin: 0 auto;
  }

  .header-brand {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .header-logo {
    font-size: 2rem;
  }

  .header-title {
    font-size: 1.5rem;
    font-weight: 600;
    margin: 0;
  }

  .header-actions {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .header-notification {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    background-color: rgba(255, 255, 255, 0.1);
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    cursor: pointer;
    transition: background-color 0.2s;
    color: white;
  }

  .header-notification:hover {
    background-color: rgba(255, 255, 255, 0.2);
  }

  .notification-icon {
    font-size: 1.25rem;
  }

  .notification-count {
    background-color: #EF4444;
    color: white;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.125rem 0.5rem;
    border-radius: 9999px;
    min-width: 1.5rem;
    text-align: center;
  }
</style>

// frontend/src/components/Header.vue
<template>
  <header class="header">
    <div class="header-left">
      <span class="page-title">{{ pageTitle }}</span>
    </div>
    <div class="header-right">
      <div class="user-info">
        <span class="role-badge">{{ authStore.roleText }}</span>
        <span class="username">{{ authStore.user?.name }}</span>
      </div>
      <el-button type="text" @click="handleLogout" class="logout-btn">
        <el-icon><component :is="LogOut" /></el-icon>
        <span>退出</span>
      </el-button>
    </div>
  </header>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { LogOut } from '@element-plus/icons-vue'
import { useAuthStore } from '../stores/auth'
import { ElMessage } from 'element-plus'

const route = useRoute()
const authStore = useAuthStore()

const pageTitleMap = {
  '/': '首页',
  '/activities': '活动管理',
  '/applications': '报名处理',
  '/posts': '岗位分配',
  '/exceptions': '异常处理'
}

const pageTitle = computed(() => {
  for (const path of Object.keys(pageTitleMap)) {
    if (route.path.startsWith(path)) {
      return pageTitleMap[path]
    }
  }
  return '社区志愿服务站'
})

function handleLogout() {
  authStore.logout()
  ElMessage.success('已退出登录')
}
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
  height: 60px;
  background: white;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.page-title {
  font-size: 18px;
  font-weight: 600;
  color: #333;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 20px;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 10px;
}

.role-badge {
  padding: 4px 10px;
  background: #e6f4ff;
  color: #1890ff;
  border-radius: 12px;
  font-size: 12px;
}

.username {
  font-size: 14px;
  color: #666;
}

.logout-btn {
  color: #999;
}

.logout-btn:hover {
  color: #1890ff;
}
</style>
