// src/components/common/Timeline.tsx
import React from 'react';
import { Clock, User } from 'lucide-react';
import { formatDateTime } from '@/utils/date';

export interface TimelineItem {
  id: string;
  action: string;
  operator: string;
  operatorRole?: string;
  remark?: string;
  createdAt: string;
  beforeData?: Record<string, unknown>;
  afterData?: Record<string, unknown>;
}

interface TimelineProps {
  items: TimelineItem[];
  title?: string;
}

export const Timeline: React.FC<TimelineProps> = ({ items, title }) => {
  if (items.length === 0) {
    return (
      <div className="text-center py-8 text-gray-500">
        <Clock className="w-12 h-12 mx-auto mb-2 opacity-30" />
        <p>暂无记录</p>
      </div>
    );
  }

  return (
    <div className="space-y-1">
      {title && <h4 className="text-sm font-medium text-gray-700 mb-3">{title}</h4>}
      <div className="relative">
        <div className="absolute left-4 top-2 bottom-2 w-0.5 bg-gray-200" />
        {items.map((item, index) => (
          <div key={item.id} className="relative pl-10 pb-6 last:pb-0">
            <div
              className={`absolute left-2 w-5 h-5 rounded-full border-2 ${
                index === 0
                  ? 'border-cinema-red bg-white'
                  : 'border-gray-300 bg-white'
              }`}
            />
            <div className="bg-gray-50 rounded-lg p-4">
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-gray-900">{item.action}</span>
                </div>
                <div className="flex items-center gap-1 text-xs text-gray-500">
                  <Clock className="w-3 h-3" />
                  {formatDateTime(item.createdAt)}
                </div>
              </div>
              <div className="flex items-center gap-1 text-sm text-gray-600 mb-2">
                <User className="w-3 h-3" />
                {item.operator}
                {item.operatorRole && <span className="text-gray-400">（{item.operatorRole}）</span>}
              </div>
              {item.remark && <p className="text-sm text-gray-600 bg-white rounded px-3 py-2 border border-gray-100">{item.remark}</p>}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// frontend/src/components/TimeLine.vue
<script setup lang="ts">
import type { OperationLog } from '../types'
import { ACTION_LABEL, ROLE_LABEL } from '../types/enums'

defineProps<{
  logs: OperationLog[]
}>()

function getTime(log: OperationLog): string {
  return log.timestamp || log.operateTime || ''
}

function getDetail(log: OperationLog): string {
  if (log.detail) return log.detail
  if (log.details && typeof log.details === 'object') {
    return Object.entries(log.details)
      .map(([k, v]) => `${k}: ${v}`)
      .join('; ')
  }
  return ''
}
</script>

<template>
  <div class="relative pl-6">
    <div
      v-for="(log, index) in logs"
      :key="log.id"
      class="relative pb-4 last:pb-0"
    >
      <div
        class="absolute -left-6 top-1.5 w-3 h-3 bg-blue-900 border-2 border-white rounded-full z-10"
      ></div>
      <div
        v-if="index !== logs.length - 1"
        class="absolute -left-[22px] top-4 bottom-0 w-px bg-gray-300"
      ></div>

      <div class="ml-2">
        <div class="flex items-center gap-2 text-xs text-gray-500 mb-1">
          <span>{{ getTime(log) }}</span>
          <span class="text-gray-300">|</span>
          <span class="font-medium text-gray-700">{{ log.operatorName }}</span>
          <span class="text-gray-400">({{ ROLE_LABEL[log.operatorRole] }})</span>
        </div>
        <div class="text-sm font-medium text-gray-900 mb-1">
          {{ ACTION_LABEL[log.action] }}
        </div>
        <div v-if="getDetail(log)" class="text-sm text-gray-600">
          {{ getDetail(log) }}
        </div>
      </div>
    </div>
  </div>
</template>
