// src/components/common/Timeline.vue
<template>
  <div class="space-y-4">
    <div
      v-for="(item, index) in items"
      :key="item.id"
      class="flex gap-4"
    >
      <div class="flex-shrink-0 flex flex-col items-center">
        <div
          :class="[
            'w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium',
            getAvatarClass(item.operatorRole)
          ]"
        >
          {{ getAvatarText(item.operator) }}
        </div>
        <div
          v-if="index < items.length - 1"
          class="w-0.5 h-full bg-gray-200 mt-2"
        />
      </div>
      
      <div class="flex-1 pb-6">
        <div class="flex items-start justify-between gap-2">
          <div>
            <div class="flex items-center gap-2">
              <span class="font-medium text-gray-900">{{ item.operator }}</span>
              <span :class="getRoleClass(item.operatorRole)">
                {{ getRoleText(item.operatorRole) }}
              </span>
            </div>
            <div class="text-sm text-gray-500 mt-1">
              {{ formatTime(item.timestamp) }}
            </div>
          </div>
          <span
            v-if="item.action"
            class="text-sm font-medium text-gray-600"
          >
            {{ item.action }}
          </span>
        </div>
        
        <div class="mt-2 text-sm text-gray-700">
          {{ item.remark }}
        </div>
        
        <div
          v-if="item.fromStatus && item.toStatus"
          class="mt-2 flex items-center gap-2"
        >
          <StatusBadge :status="item.fromStatus" type="assignment" />
          <ArrowRight class="w-4 h-4 text-gray-400" />
          <StatusBadge :status="item.toStatus" type="assignment" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ArrowRight } from 'lucide-vue-next'
import type { HistoryRecord, UserRole } from '@/types'
import StatusBadge from './StatusBadge.vue'

const props = defineProps<{
  items: HistoryRecord[]
}>()

const getAvatarClass = (role: UserRole) => {
  const classes: Record<UserRole, string> = {
    project_manager: 'bg-primary-500 text-white',
    translator: 'bg-warning-500 text-white',
    reviewer: 'bg-success-500 text-white',
  }
  return classes[role]
}

const getAvatarText = (name: string) => {
  return name.charAt(0)
}

const getRoleClass = (role: UserRole) => {
  const classes: Record<UserRole, string> = {
    project_manager: 'px-2 py-0.5 rounded text-xs bg-primary-100 text-primary-700',
    translator: 'px-2 py-0.5 rounded text-xs bg-warning-100 text-warning-700',
    reviewer: 'px-2 py-0.5 rounded text-xs bg-success-100 text-success-700',
  }
  return classes[role]
}

const getRoleText = (role: UserRole) => {
  const texts: Record<UserRole, string> = {
    project_manager: '项目经理',
    translator: '译员',
    reviewer: '审校',
  }
  return texts[role]
}

const formatTime = (timestamp: string) => {
  const date = new Date(timestamp)
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const days = Math.floor(diff / (1000 * 60 * 60 * 24))
  
  if (days === 0) {
    const hours = Math.floor(diff / (1000 * 60 * 60))
    if (hours === 0) {
      const minutes = Math.floor(diff / (1000 * 60))
      return `${minutes}分钟前`
    }
    return `${hours}小时前`
  } else if (days === 1) {
    return '昨天'
  } else if (days < 7) {
    return `${days}天前`
  } else {
    return date.toLocaleDateString('zh-CN')
  }
}
</script>

// src/components/shared/Timeline.tsx
import { cn } from '@/lib/utils'

interface TimelineItem {
  id: string
  title: string
  subtitle?: string
  timestamp: string
  highlight?: boolean
}

interface TimelineProps {
  items: TimelineItem[]
}

function getRelativeTime(timestamp: string): string {
  const now = Date.now()
  const then = new Date(timestamp).getTime()
  const diff = now - then

  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return '刚刚'
  if (minutes < 60) return `${minutes}分钟前`
  if (hours < 24) return `${hours}小时前`
  if (days < 30) return `${days}天前`
  return new Date(timestamp).toLocaleDateString('zh-CN')
}

export default function Timeline({ items }: TimelineProps) {
  return (
    <div className="relative">
      {items.map((item, index) => (
        <div key={item.id} className="relative flex gap-3 pb-6 last:pb-0">
          <div className="flex flex-col items-center">
            <div
              className={cn(
                'w-2.5 h-2.5 rounded-full shrink-0 mt-1.5',
                item.highlight ? 'bg-orange-500' : 'bg-slate-300'
              )}
            />
            {index < items.length - 1 && (
              <div className="w-px flex-1 bg-slate-200 mt-1" />
            )}
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-baseline justify-between gap-2">
              <p className="text-sm font-medium text-slate-900 truncate">{item.title}</p>
              <span className="text-xs text-slate-400 shrink-0">{getRelativeTime(item.timestamp)}</span>
            </div>
            {item.subtitle && (
              <p className="text-xs text-slate-500 mt-0.5">{item.subtitle}</p>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}
