// src/components/layout/Sidebar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'
import { LayoutDashboard, ShieldCheck, AlertTriangle, Truck, Factory } from 'lucide-vue-next'
import { useStaffStore } from '@/stores/staff'
import type { RoleType } from '@/types'

const route = useRoute()
const router = useRouter()
const staffStore = useStaffStore()

const navItems = [
  { name: '首页仪表盘', icon: LayoutDashboard, path: '/' },
  { name: '质检放行', icon: ShieldCheck, path: '/qc' },
  { name: '异常提醒', icon: AlertTriangle, path: '/exceptions' },
  { name: '客户回寄', icon: Truck, path: '/shipping' },
]

const roles: { key: RoleType; label: string }[] = [
  { key: 'cs', label: '接单客服' },
  { key: 'designer', label: '数字设计师' },
  { key: 'qc', label: '质检员' },
]

function isActive(path: string) {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}
</script>

<template>
  <aside class="fixed left-0 top-0 z-40 flex h-screen w-60 flex-col bg-factory-surface border-r border-factory-border">
    <div class="flex items-center gap-2 px-5 py-5 border-b border-factory-border">
      <Factory :size="22" class="text-warn-orange" />
      <h1 class="text-base font-bold text-white tracking-wide">义齿质检放行</h1>
    </div>

    <nav class="mt-2 flex-1 space-y-1 px-3">
      <button
        v-for="item in navItems"
        :key="item.path"
        class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors"
        :class="isActive(item.path)
          ? 'bg-factory-surface-light text-warn-orange border-l-[3px] border-warn-orange'
          : 'text-gray-400 hover:bg-factory-surface-light hover:text-gray-200 border-l-[3px] border-transparent'"
        @click="router.push(item.path)"
      >
        <component :is="item.icon" :size="18" />
        <span>{{ item.name }}</span>
      </button>
    </nav>

    <div class="border-t border-factory-border px-4 py-4">
      <p class="mb-2 text-xs text-gray-500 uppercase tracking-wider">当前角色</p>
      <div class="flex flex-wrap gap-2">
        <button
          v-for="role in roles"
          :key="role.key"
          class="rounded-md px-2.5 py-1 text-xs font-medium transition-colors"
          :class="staffStore.currentRole === role.key
            ? 'bg-warn-orange text-white'
            : 'bg-factory-surface-light text-gray-400 hover:text-gray-200'"
          @click="staffStore.switchRole(role.key)"
        >
          {{ role.label }}
        </button>
      </div>
    </div>
  </aside>
</template>

// src/components/Layout/Sidebar.tsx
import { LayoutDashboard, Package, FileCheck, Truck, Settings, User } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import { useAuthStore } from '@/stores/auth';

const navItems = [
  { icon: LayoutDashboard, label: '工作台', path: '/' },
  { icon: Package, label: '配件管理', path: '/parts' },
  { icon: FileCheck, label: '签认中心', path: '/signoff' },
  { icon: Truck, label: '设备档案', path: '/equipment' },
];

export function Sidebar() {
  const { currentUser } = useAuthStore();

  return (
    <aside className="w-64 bg-slate-900 text-white min-h-screen flex flex-col">
      <div className="p-6 border-b border-slate-700">
        <h1 className="text-xl font-bold text-blue-400">叉车维保系统</h1>
        <p className="text-sm text-slate-400 mt-1">停机处置与复工签认</p>
      </div>

      <nav className="flex-1 p-4">
        <ul className="space-y-2">
          {navItems.map((item) => (
            <li key={item.path}>
              <NavLink
                to={item.path}
                className={({ isActive }) =>
                  `flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200 ${
                    isActive
                      ? 'bg-blue-600 text-white shadow-lg'
                      : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                  }`
                }
              >
                <item.icon size={20} />
                <span className="font-medium">{item.label}</span>
              </NavLink>
            </li>
          ))}
        </ul>
      </nav>

      <div className="p-4 border-t border-slate-700">
        <div className="flex items-center gap-3 px-4 py-3 bg-slate-800 rounded-lg">
          <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center">
            <User size={20} />
          </div>
          <div>
            <p className="font-medium">{currentUser?.name}</p>
            <p className="text-xs text-slate-400">
              {currentUser?.role === 'manager' && '维保主管'}
              {currentUser?.role === 'technician' && '现场技师'}
              {currentUser?.role === 'warehouse' && '仓管'}
            </p>
          </div>
        </div>
        <button className="w-full mt-3 flex items-center justify-center gap-2 px-4 py-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors">
          <Settings size={18} />
          <span>设置</span>
        </button>
      </div>
    </aside>
  );
}
