// components/TopBar.vue
<template>
  <header class="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
    <div class="flex items-center gap-4">
      <h2 class="text-lg font-semibold text-gray-800">{{ pageTitle }}</h2>
    </div>
    <div class="flex items-center gap-4">
      <div class="relative">
        <button
          @click="showDropdown = !showDropdown"
          class="flex items-center gap-3 px-4 py-2 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
        >
          <div class="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center text-sm font-medium">
            {{ appStore.currentUser.name.charAt(0) }}
          </div>
          <div class="text-left">
            <div class="text-sm font-medium text-gray-800">{{ appStore.currentUser.name }}</div>
            <div class="text-xs text-gray-500">{{ getRoleText(appStore.currentRole) }}</div>
          </div>
          <ChevronDown class="w-4 h-4 text-gray-500" />
        </button>
        <div
          v-if="showDropdown"
          class="absolute right-0 mt-2 w-56 bg-white rounded-lg shadow-lg border border-gray-200 py-2 z-50"
        >
          <div class="px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider">切换角色</div>
          <button
            v-for="user in appStore.userList"
            :key="user.id"
            @click="switchRole(user.role)"
            class="w-full px-4 py-2 text-left hover:bg-gray-50 flex items-center gap-3"
            :class="{ 'bg-slate-50': user.role === appStore.currentRole }"
          >
            <div class="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center text-sm font-medium">
              {{ user.name.charAt(0) }}
            </div>
            <div>
              <div class="text-sm font-medium text-gray-800">{{ user.name }}</div>
              <div class="text-xs text-gray-500">{{ getRoleText(user.role) }}</div>
            </div>
          </button>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ChevronDown } from 'lucide-vue-next'
import { useAppStore } from '../stores/app'
import { useFormat } from '../composables/useFormat'
import { useRoute } from 'vue-router'

const appStore = useAppStore()
const { getRoleText } = useFormat()
const route = useRoute()

const showDropdown = ref(false)

const pageTitle = computed(() => {
  const titles: Record<string, string> = {
    '/': '工作台',
    '/orders': '订单同步',
    '/customs': '报关资料',
    '/inventory': '库存管理',
    '/data': '数据管理'
  }
  return titles[route.path] || '工作台'
})

const switchRole = (role: any) => {
  appStore.setRole(role)
  showDropdown.value = false
}
</script>

// src/components/layout/TopBar.tsx

import { useNavigate } from 'react-router-dom';
import { Home, RotateCcw, User } from 'lucide-react';
import { Role } from '../../types';
import { ROLE_CONFIG } from '../../utils/constants';
import { useData } from '../../contexts/DataContext';

interface TopBarProps {
  role: Role;
}

export function TopBar({ role }: TopBarProps) {
  const navigate = useNavigate();
  const config = ROLE_CONFIG[role];
  const roleColor = config.color;
  const { resetData } = useData();

  const handleReset = () => {
    if (confirm('确定要重置所有数据吗？这将恢复初始演示数据。')) {
      resetData();
      window.location.reload();
    }
  };

  return (
    <header className={`bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between`}>
      <div className="flex items-center gap-4">
        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors"
        >
          <Home className="w-5 h-5" />
          <span className="text-sm font-medium">返回首页</span>
        </button>
        
        <div className="h-6 w-px bg-gray-300" />
        
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-lg bg-${roleColor} flex items-center justify-center text-white font-semibold`}>
            {config.name.charAt(0)}
          </div>
          <div>
            <p className="text-sm font-semibold text-gray-900">{config.name}</p>
            <p className="text-xs text-gray-500">当前角色</p>
          </div>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <button
          onClick={handleReset}
          className="flex items-center gap-2 px-3 py-2 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <RotateCcw className="w-4 h-4" />
          <span>重置数据</span>
        </button>

        <div className="h-8 w-px bg-gray-300" />

        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gray-200 rounded-full flex items-center justify-center">
            <User className="w-4 h-4 text-gray-600" />
          </div>
          <div className="text-sm">
            <p className="font-medium text-gray-900">系统管理员</p>
            <p className="text-xs text-gray-500">在线</p>
          </div>
        </div>
      </div>
    </header>
  );
}
