// src/pages/bookings/new.tsx
import { GetServerSideProps } from 'next';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import prisma from '@/lib/db';
import { requireAuth, serializeUser } from '@/lib/auth';
import Layout from '@/components/Layout';

const packageTypes = ['标准套餐', '豪华套餐', '高级套餐', '基础套餐'];

export default function NewBookingPage({ user }: { user: ReturnType<typeof serializeUser> }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    companyName: '',
    contactPerson: '',
    contactPhone: '',
    scheduledDate: '',
    expectedCount: 50,
    packageType: '标准套餐',
    pricePerPerson: 380,
    remark: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/bookings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        const data = await res.json();
        router.push(`/bookings/${data.id}`);
      } else {
        alert('创建失败');
      }
    } catch (error) {
      alert('网络错误');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout user={user} title="新建预约">
      <div className="max-w-3xl mx-auto">
      <div className="space-y-6">
        <div className="flex items-center space-x-4">
          <Link href="/" className="text-gray-500 hover:text-gray-700">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <h1 className="text-2xl font-bold text-gray-900">新建团检预约</h1>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  单位名称 *
                </label>
                <input
                  type="text"
                  value={formData.companyName}
                  onChange={(e) => setFormData({ ...formData, companyName: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入单位名称"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  联系人 *
                </label>
                <input
                  type="text"
                  value={formData.contactPerson}
                  onChange={(e) => setFormData({ ...formData, contactPerson: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入联系人姓名"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  联系电话 *
                </label>
                <input
                  type="tel"
                  value={formData.contactPhone}
                  onChange={(e) => setFormData({ ...formData, contactPhone: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入联系电话"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  预约日期 *
                </label>
                <input
                  type="date"
                  value={formData.scheduledDate}
                  onChange={(e) => setFormData({ ...formData, scheduledDate: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  预计人数 *
                </label>
                <input
                  type="number"
                  value={formData.expectedCount}
                  onChange={(e) => setFormData({ ...formData, expectedCount: parseInt(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  min="1"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  套餐类型
                </label>
                <select
                  value={formData.packageType}
                  onChange={(e) => setFormData({ ...formData, packageType: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                >
                  {packageTypes.map((type) => (
                    <option key={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  单价 (元/人)
                </label>
                <input
                  type="number"
                  value={formData.pricePerPerson}
                  onChange={(e) => setFormData({ ...formData, pricePerPerson: parseFloat(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  min="0"
                />
              </div>

              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  备注
                </label>
                <textarea
                  value={formData.remark}
                  onChange={(e) => setFormData({ ...formData, remark: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  rows={3}
                  placeholder="请输入备注信息"
                />
              </div>
            </div>

            <div className="flex justify-end space-x-4 pt-4 border-t border-gray-100">
              <Link
                href="/"
                className="px-6 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition"
              >
                取消
              </Link>
              <button
                type="submit"
                disabled={loading}
                className="px-6 py-2 bg-blue-500 text-white font-medium rounded-lg hover:bg-blue-600 transition disabled:opacity-50"
              >
                {loading ? '创建中...' : '创建预约'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const authResult = await requireAuth(context);
  if ('redirect' in authResult) {
    return { redirect: authResult.redirect };
  }

  return {
    props: {
      user: serializeUser(authResult.user),
    },
  };
};

// src/routes/consumption/new/+page.svelte
<script lang="ts">
	import Layout from '$lib/components/Layout.svelte';
	import { ArrowLeft, Save, X } from '@lucide/svelte';
	import type { PageData } from './$types';
	import type { ActionData } from './$types';

	let { data, form }: { data: PageData; form: ActionData | null } = $props();

	let studentId = $state(form?.studentId || data.preselectedStudentId || '');
	let courseName = $state(form?.courseName || '');
	let hours = $state(form?.hours || '');
	let remark = $state(form?.remark || '');
</script>

<Layout user={data.user}>
	<div class="max-w-2xl mx-auto space-y-6">
		<div class="flex items-center gap-4">
			<a
				href="/consumption"
				class="p-2 rounded-lg text-gray-600 hover:bg-gray-100 transition-colors"
			>
				<ArrowLeft size={20} />
			</a>
			<div>
				<h1 class="text-2xl font-bold text-gray-800">新增课消</h1>
				<p class="text-gray-500 mt-1">创建新的课包消耗记录</p>
			</div>
		</div>

		{#if form?.error}
			<div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
				{form.error}
			</div>
		{/if}

		<form method="POST" class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 space-y-6">
			<div>
				<label for="studentId" class="block text-sm font-medium text-gray-700 mb-2">
					选择学生 <span class="text-red-500">*</span>
				</label>
				<select
					id="studentId"
					name="studentId"
					bind:value={studentId}
					class="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-teal-500 outline-none transition-all bg-white"
					required
				>
					<option value="">请选择学生</option>
					{#each data.students as student (student.id)}
						<option value={student.id}>
							{student.name} (剩余 {student.remainingHours} 课时)
						</option>
					{/each}
				</select>
			</div>

			<div>
				<label for="courseName" class="block text-sm font-medium text-gray-700 mb-2">
					课程名称 <span class="text-red-500">*</span>
				</label>
				<input
					type="text"
					id="courseName"
					name="courseName"
					bind:value={courseName}
					placeholder="例如：钢琴一对一"
					class="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-teal-500 outline-none transition-all"
					required
				/>
			</div>

			<div>
				<label for="hours" class="block text-sm font-medium text-gray-700 mb-2">
					课时数 <span class="text-red-500">*</span>
				</label>
				<input
					type="number"
					id="hours"
					name="hours"
					bind:value={hours}
					min="0.5"
					step="0.5"
					placeholder="例如：1"
					class="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-teal-500 outline-none transition-all"
					required
				/>
			</div>

			<div>
				<label for="remark" class="block text-sm font-medium text-gray-700 mb-2">
					备注
				</label>
				<textarea
					id="remark"
					name="remark"
					bind:value={remark}
					rows="3"
					placeholder="可选：添加备注信息"
					class="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-teal-500 outline-none transition-all resize-none"
				/>
			</div>

			<div class="flex items-center justify-end gap-3 pt-4 border-t border-gray-100">
				<a
					href="/consumption"
					class="inline-flex items-center px-5 py-2.5 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors font-medium"
				>
					<X size={16} class="mr-2" />
					取消
				</a>
				<button
					type="submit"
					class="inline-flex items-center px-5 py-2.5 bg-teal-700 text-white rounded-lg hover:bg-teal-800 transition-colors font-medium shadow-sm"
				>
					<Save size={16} class="mr-2" />
					提交
				</button>
			</div>
		</form>
	</div>
</Layout>
