// src/app/dashboard/page.tsx
'use client'

import Layout from '@/components/Layout'
import StatusBadge from '@/components/StatusBadge'
import { formatDate } from '@/lib/utils'
import { useAuthStore } from '@/store/authStore'
import { FileText, ShoppingCart, ClipboardCheck, AlertTriangle, ChevronRight, TrendingUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import Link from 'next/link'

interface Order {
  id: string
  orderNumber: string
  status: string
  supplier: { name: string }
  part: { name: string }
  quantity: number
  expectedDeliveryDate: string
}

interface Exception {
  id: string
  exceptionNumber: string
  title: string
  status: string
  purchaseOrder: { orderNumber: string }
  createdAt: string
}

export default function DashboardPage() {
  const { user } = useAuthStore()
  const [orders, setOrders] = useState<Order[]>([])
  const [exceptions, setExceptions] = useState<Exception[]>([])
  const [stats, setStats] = useState({
    orders: 0,
    exceptions: 0,
    drawings: 0,
    inspections: 0,
  })

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    try {
      const [ordersRes, exceptionsRes] = await Promise.all([
        fetch('/api/orders'),
        fetch('/api/exceptions'),
      ])

      const ordersData = await ordersRes.json()
      const exceptionsData = await exceptionsRes.json()

      setOrders(ordersData.slice(0, 5))
      setExceptions(exceptionsData.slice(0, 5))
      setStats({
        orders: ordersData.length,
        exceptions: exceptionsData.filter((e: Exception) => e.status !== 'CLOSED').length,
        drawings: 4,
        inspections: 2,
      })
    } catch (error) {
      console.error('Failed to fetch data:', error)
    }
  }

  const statCards = [
    { label: '外协订单', value: stats.orders, icon: ShoppingCart, href: '/orders', color: 'bg-blue-500' },
    { label: '待处理异常', value: stats.exceptions, icon: AlertTriangle, href: '/exceptions', color: 'bg-red-500' },
    { label: '图纸版本', value: stats.drawings, icon: FileText, href: '/drawings', color: 'bg-purple-500' },
    { label: '检验记录', value: stats.inspections, icon: ClipboardCheck, href: '/inspections', color: 'bg-green-500' },
  ]

  return (
    <Layout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">工作台</h1>
          <p className="text-gray-500 mt-1">欢迎回来，{user?.name}</p>
        </div>

        <div className="grid grid-cols-4 gap-6">
          {statCards.map((stat) => {
            const Icon = stat.icon
            return (
              <Link
                key={stat.label}
                href={stat.href}
                className="card p-6 hover:shadow-md transition-shadow"
              >
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm text-gray-500 mb-1">{stat.label}</p>
                    <p className="text-3xl font-bold text-gray-900">{stat.value}</p>
                  </div>
                  <div className={`w-12 h-12 ${stat.color} rounded-xl flex items-center justify-center`}>
                    <Icon size={24} className="text-white" />
                  </div>
                </div>
              </Link>
            )
          })}
        </div>

        <div className="grid grid-cols-2 gap-6">
          <div className="card p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900">最近订单</h2>
              <Link href="/orders" className="text-primary-600 text-sm flex items-center gap-1">
                查看全部 <ChevronRight size={16} />
              </Link>
            </div>
            <div className="space-y-3">
              {orders.map((order) => (
                <div key={order.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium text-gray-900">{order.orderNumber}</p>
                    <p className="text-sm text-gray-500">{order.part.name} · {order.quantity}件</p>
                  </div>
                  <StatusBadge type="order" status={order.status} />
                </div>
              ))}
            </div>
          </div>

          <div className="card p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900">异常单</h2>
              <Link href="/exceptions" className="text-primary-600 text-sm flex items-center gap-1">
                查看全部 <ChevronRight size={16} />
              </Link>
            </div>
            <div className="space-y-3">
              {exceptions.map((exception) => (
                <Link
                  key={exception.id}
                  href={`/exceptions/${exception.id}`}
                  className="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <p className="font-medium text-gray-900">{exception.exceptionNumber}</p>
                        <StatusBadge type="exception" status={exception.status} />
                      </div>
                      <p className="text-sm text-gray-500 mt-1 line-clamp-1">{exception.title}</p>
                    </div>
                  </div>
                  <p className="text-xs text-gray-400 mt-2">{formatDate(exception.createdAt)}</p>
                </Link>
              ))}
            </div>
          </div>
        </div>

        <div className="card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center">
              <TrendingUp size={20} className="text-yellow-600" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">需要关注</h2>
              <p className="text-sm text-gray-500">当前系统中的关键事项</p>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div className="p-4 bg-yellow-50 rounded-xl border border-yellow-200">
              <p className="font-medium text-yellow-800">图纸变更待确认</p>
              <p className="text-2xl font-bold text-yellow-900 mt-2">1</p>
              <p className="text-sm text-yellow-600 mt-1">订单 PO-2026-06-001</p>
            </div>
            <div className="p-4 bg-red-50 rounded-xl border border-red-200">
              <p className="font-medium text-red-800">尺寸超差待处理</p>
              <p className="text-2xl font-bold text-red-900 mt-2">1</p>
              <p className="text-sm text-red-600 mt-1">订单 PO-2026-06-002</p>
            </div>
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-200">
              <p className="font-medium text-blue-800">让步接收复检中</p>
              <p className="text-2xl font-bold text-blue-900 mt-2">1</p>
              <p className="text-sm text-blue-600 mt-1">订单 PO-2026-06-003</p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  )
}

// src/pages/Dashboard.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useApi } from '@/composables/useApi'
import { ArrowRight, ClipboardCheck, FileText, Clock, AlertTriangle, Plus, Eye } from 'lucide-vue-next'
import Login from '@/pages/Login.vue'
import RoleBadge from '@/components/RoleBadge.vue'
import StatusBadge from '@/components/StatusBadge.vue'

const router = useRouter()
const auth = useAuthStore()
const api = useApi()

const stats = ref<any>({})
const loading = ref(false)
const recentActions = ref<any[]>([])
const overdueItems = ref<any[]>([])

const roleEntries = computed(() => {
  const r = auth.role
  if (r === '繁育员') {
    return [
      { label: '新建转栏', desc: '为断奶仔猪创建转栏记录', icon: Plus, path: '/transfer/new', color: 'border-emerald-500/40 hover:border-emerald-500/80' },
      { label: '待确认转栏', desc: `待处理 ${stats.value.pending_transfer || 0} 条`, icon: ArrowRight, path: '/transfer?status=pending_transfer', color: 'border-amber-500/40 hover:border-amber-500/80' },
      { label: '待提交评估', desc: `待提交 ${stats.value.transferred || 0} 条`, icon: ClipboardCheck, path: '/transfer?status=transferred', color: 'border-blue-500/40 hover:border-blue-500/80' },
    ]
  }
  if (r === '兽医') {
    return [
      { label: '待评估仔猪', desc: `待评估 ${stats.value.pending_assessment || 0} 条`, icon: ClipboardCheck, path: '/assessment?status=pending_assessment', color: 'border-orange-500/40 hover:border-orange-500/80' },
      { label: '评估历史', desc: `已评估 ${stats.value.assessed || 0} 条`, icon: Eye, path: '/assessment', color: 'border-blue-500/40 hover:border-blue-500/80' },
    ]
  }
  return [
    { label: '待审批淘汰', desc: `待审批 ${stats.value.pending_approval || 0} 条`, icon: FileText, path: '/assessment?status=pending_approval', color: 'border-purple-500/40 hover:border-purple-500/80' },
    { label: '全场转栏记录', desc: `共 ${stats.value.totalTransfers || 0} 条`, icon: Eye, path: '/transfer', color: 'border-slate-500/40 hover:border-slate-500/80' },
    { label: '操作日志', desc: '查看所有操作记录', icon: FileText, path: '/log', color: 'border-amber-500/40 hover:border-amber-500/80' },
  ]
})

const overdueCount = computed(() => stats.value.overdueMyTasks || 0)

onMounted(fetchData)

watch(() => auth.isLoggedIn, (val) => {
  if (val) fetchData()
})

async function fetchData() {
  if (!auth.isLoggedIn) return
  loading.value = true
  try {
    const res = await api.getStats(auth.role!)
    const data = res.data || res
    stats.value = data

    const logRes = await api.getLogs({ role: auth.role!, page: 1, pageSize: 5 })
    recentActions.value = (logRes.data?.list || logRes.list || []).slice(0, 5)

    if (auth.role === '繁育员') {
      const tRes = await api.getTransfers({ status: 'pending_transfer', pageSize: 50 })
      const list = tRes.data?.list || tRes.list || []
      overdueItems.value = list.filter((t: any) => t.isOverdue)
    } else if (auth.role === '兽医') {
      const aRes = await api.getAssessments({ status: 'pending_assessment', pageSize: 50 })
      const list = aRes.data?.list || aRes.list || []
      overdueItems.value = list.filter((a: any) => a.isOverdue)
    } else if (auth.role === '场长') {
      const aRes = await api.getAssessments({ status: 'pending_approval', pageSize: 50 })
      const list = aRes.data?.list || aRes.list || []
      overdueItems.value = list.filter((a: any) => a.isOverdue)
    }
  } catch (e) {
    console.error('Failed to fetch dashboard data:', e)
  } finally {
    loading.value = false
  }
}

function goTransferDetail(id: number) {
  router.push(`/transfer/${id}`)
}

function goAssessmentDetail(id: number) {
  router.push(`/assessment/${id}`)
}
</script>

<template>
  <Login v-if="!auth.isLoggedIn" />
  <div v-else class="space-y-6">
    <div>
      <h2 class="text-xl font-semibold text-slate-100">工作台</h2>
      <p class="text-sm text-slate-500 mt-1">欢迎回来，{{ auth.name }}</p>
    </div>

    <div
      v-if="overdueCount > 0"
      class="bg-red-500/10 border border-red-500/30 rounded-xl p-4 flex items-start gap-3"
    >
      <AlertTriangle :size="20" class="text-red-400 shrink-0 mt-0.5" />
      <div class="flex-1">
        <div class="text-sm font-medium text-red-300">您有 {{ overdueCount }} 项超时任务</div>
        <div class="text-xs text-red-400/80 mt-1">请尽快处理，避免影响后续流程</div>
        <div v-if="overdueItems.length > 0" class="mt-3 space-y-2">
          <div
            v-for="item in overdueItems.slice(0, 3)"
            :key="item.id"
            class="flex items-center gap-3 bg-red-500/10 rounded-lg px-3 py-2 cursor-pointer hover:bg-red-500/20 transition-colors"
            @click="item.ear_tag ? goTransferDetail(item.id) : goAssessmentDetail(item.id)"
          >
            <span class="text-sm text-red-200">{{ item.ear_tag }}</span>
            <StatusBadge :status="item.status" />
            <span class="text-xs text-red-400 ml-auto">已超时</span>
          </div>
        </div>
      </div>
    </div>

    <div>
      <h3 class="text-sm font-medium text-slate-400 mb-3">处理入口</h3>
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div
          v-for="entry in roleEntries"
          :key="entry.label"
          :class="[
            'card border cursor-pointer transition-all duration-200 hover:shadow-lg',
            entry.color
          ]"
          @click="router.push(entry.path)"
        >
          <div class="flex items-center gap-3 mb-2">
            <component :is="entry.icon" :size="20" class="text-slate-300" />
            <span class="text-sm font-semibold text-slate-200">{{ entry.label }}</span>
          </div>
          <p class="text-xs text-slate-500">{{ entry.desc }}</p>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
      <div class="card text-center">
        <div class="text-2xl font-bold text-amber-400">{{ stats.pending_transfer || 0 }}</div>
        <div class="text-xs text-slate-500 mt-1">待转栏</div>
      </div>
      <div class="card text-center">
        <div class="text-2xl font-bold text-blue-400">{{ stats.transferred || 0 }}</div>
        <div class="text-xs text-slate-500 mt-1">已转栏</div>
      </div>
      <div class="card text-center">
        <div class="text-2xl font-bold text-orange-400">{{ stats.pending_assessment || 0 }}</div>
        <div class="text-xs text-slate-500 mt-1">待评估</div>
      </div>
      <div class="card text-center">
        <div class="text-2xl font-bold text-purple-400">{{ stats.pending_approval || 0 }}</div>
        <div class="text-xs text-slate-500 mt-1">待审批</div>
      </div>
    </div>

    <div class="card">
      <h3 class="text-sm font-medium text-slate-300 mb-4">最近动态</h3>
      <div v-if="loading" class="text-sm text-slate-500 py-4 text-center">加载中...</div>
      <div v-else-if="recentActions.length === 0" class="text-sm text-slate-500 py-4 text-center">暂无动态</div>
      <div v-else class="space-y-3">
        <div
          v-for="(item, idx) in recentActions"
          :key="idx"
          class="flex items-center gap-3 py-2 border-b border-slate-700/50 last:border-0"
        >
          <Clock :size="14" class="text-slate-500 shrink-0" />
          <span class="text-sm text-slate-300 flex-1">{{ item.detail || item.action }}</span>
          <RoleBadge :role="item.operator_role" />
          <span class="text-xs text-slate-600">{{ item.createdAt || item.created_at }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
