// pc-shop/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <div class="login-header">
        <div class="logo-icon">🖥️</div>
        <h1 class="login-title">电脑装机店管理系统</h1>
        <p class="login-subtitle">配件到货 · 装机排程 · 异常追踪</p>
      </div>
      
      <form @submit.prevent="handleLogin" class="login-form">
        <div class="form-row">
          <label class="form-label">账号</label>
          <div class="form-input">
            <input v-model="username" type="text" placeholder="请输入账号" required />
          </div>
        </div>
        <div class="form-row">
          <label class="form-label">密码</label>
          <div class="form-input">
            <input v-model="password" type="password" placeholder="请输入密码" required />
          </div>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width:100%;padding:10px;margin-top:8px">
          登录系统
        </button>
        
        <p v-if="loginError" class="text-danger text-sm mt-8 text-center">{{ loginError }}</p>
      </form>
      
      <div class="divider"></div>
      
      <div class="role-entries">
        <h4 class="text-sm text-muted mb-12">快速角色切换入口（原型演示）</h4>
        <div class="role-grid">
          <button v-for="u in roleUsers" :key="u.role" class="role-card" @click="quickLogin(u)">
            <div class="role-avatar" :class="'avatar-'+u.role">{{ u.avatar }}</div>
            <div>
              <div class="role-name font-semibold">{{ u.name }}</div>
              <div class="text-xs text-muted">{{ u.roleName }}</div>
              <div class="text-xs text-muted mt-4">账号: {{ u.username }} / 123456</div>
            </div>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/store/auth'

const router = useRouter()
const auth = useAuthStore()

const username = ref('')
const password = ref('')
const loginError = ref('')

const roleUsers = auth.users.map(u => u)

function handleLogin() {
  loginError.value = ''
  if (auth.login(username.value, password.value)) {
    router.push('/dashboard')
  } else {
    loginError.value = '账号或密码错误'
  }
}

function quickLogin(u) {
  auth.login(u.username, u.password)
  router.push('/dashboard')
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
}

.login-card {
  background: white;
  border-radius: 16px;
  padding: 36px;
  width: 100%;
  max-width: 520px;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
}

.login-header {
  text-align: center;
  margin-bottom: 28px;
}

.logo-icon {
  font-size: 48px;
  margin-bottom: 8px;
}

.login-title {
  font-size: 24px;
  font-weight: 700;
  color: #1f2937;
}

.login-subtitle {
  color: #6b7280;
  margin-top: 6px;
  font-size: 14px;
}

.login-form {
  margin-bottom: 24px;
}

.role-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
}

.role-card {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  text-align: left;
  transition: all 0.15s;
  background: #fafafa;
}

.role-card:hover {
  background: #eff6ff;
  border-color: #bfdbfe;
}

.role-avatar {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  color: white;
  flex-shrink: 0;
}

.avatar-manager { background: #2563eb; }
.avatar-sales { background: #0891b2; }
.avatar-warehouse { background: #16a34a; }
.avatar-tech { background: #7c3aed; }
.avatar-service { background: #d97706; }

.role-name {
  font-size: 14px;
}

.mt-4 { margin-top: 4px; }
.mb-12 { margin-bottom: 12px; }
</style>

// src/pages/Login.svelte
<script lang="ts">
  import { getUserByUsername } from '$lib/database'
  import { User, Lock, LogIn, Eye, EyeOff } from 'lucide-svelte'
  import { bind } from 'svelte'
  
  let username = ''
  let password = ''
  let showPassword = false
  let error = ''
  let quickUsers = [
    { username: 'boss', password: '123456', role: '老板', color: '#4CAF50' },
    { username: 'chef', password: '123456', role: '后厨', color: '#FF9800' },
    { username: 'housekeeper', password: '123456', role: '客房阿姨', color: '#2196F3' },
    { username: 'staff', password: '123456', role: '员工', color: '#9C27B0' }
  ]
  
  async function handleLogin() {
    error = ''
    
    if (!username || !password) {
      error = '请输入用户名和密码'
      return
    }
    
    const user = getUserByUsername(username)
    
    if (!user || user.password !== password) {
      error = '用户名或密码错误'
      return
    }
    
    localStorage.setItem('currentUser', JSON.stringify(user))
    window.location.href = '/'
  }
  
  function handleQuickLogin(user: any) {
    username = user.username
    password = user.password
    handleLogin()
  }
</script>

<div class="login-page">
  <div class="login-container">
    <div class="login-header">
      <div class="logo">🏡</div>
      <h1>农家乐管理系统</h1>
      <p>住宿入住与房态交接管理</p>
    </div>
    
    <div class="quick-login">
      <h3>快捷登录</h3>
      <div class="quick-users">
        {#each quickUsers as user}
          <button 
            class="quick-user-btn"
            style="border-color: {user.color}"
            on:click={() => handleQuickLogin(user)}
          >
            <div class="user-avatar" style="background: {user.color}">
              <User class="avatar-icon" />
            </div>
            <div class="user-info">
              <div class="user-role">{user.role}</div>
              <div class="user-username">{user.username}</div>
            </div>
          </button>
        {/each}
      </div>
    </div>
    
    <div class="login-form">
      <h3>账号登录</h3>
      
      {#if error}
        <div class="error-message">
          {error}
        </div>
      {/if}
      
      <div class="form-group">
        <div class="input-wrapper">
          <User class="input-icon" />
          <input 
            type="text" 
            placeholder="用户名" 
            bind:value={username}
            on:keydown={(e) => e.key === 'Enter' && handleLogin()}
          />
        </div>
      </div>
      
      <div class="form-group">
        <div class="input-wrapper">
          <Lock class="input-icon" />
          <input 
            type={showPassword ? 'text' : 'password'} 
            placeholder="密码" 
            bind:value={password}
            on:keydown={(e) => e.key === 'Enter' && handleLogin()}
          />
          <button class="toggle-password" on:click={() => showPassword = !showPassword}>
            {#if showPassword}
              <EyeOff class="toggle-icon" />
            {:else}
              <Eye class="toggle-icon" />
            {/if}
          </button>
        </div>
      </div>
      
      <button class="login-btn" on:click={handleLogin}>
        <LogIn class="btn-icon" />
        登录系统
      </button>
    </div>
    
    <div class="login-footer">
      <p>默认密码: 123456</p>
    </div>
  </div>
</div>

<style>
  .login-page {
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 1rem;
  }
  
  .login-container {
    background: white;
    border-radius: 16px;
    padding: 2.5rem;
    box-shadow: 0 10px 40px rgba(0,0,0,0.15);
    width: 100%;
    max-width: 420px;
  }
  
  .login-header {
    text-align: center;
    margin-bottom: 2rem;
  }
  
  .logo {
    font-size: 4rem;
    margin-bottom: 1rem;
  }
  
  .login-header h1 {
    font-size: 1.5rem;
    margin: 0 0 0.5rem 0;
    color: #333;
  }
  
  .login-header p {
    color: #666;
    margin: 0;
    font-size: 0.9rem;
  }
  
  .quick-login {
    margin-bottom: 2rem;
  }
  
  .quick-login h3 {
    font-size: 0.95rem;
    color: #666;
    margin: 0 0 1rem 0;
    padding-bottom: 0.75rem;
    border-bottom: 2px solid #f0f0f0;
  }
  
  .quick-users {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.75rem;
  }
  
  .quick-user-btn {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.75rem;
    background: #f8f9fa;
    border: 2px solid #ddd;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s;
    text-align: left;
  }
  
  .quick-user-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }
  
  .user-avatar {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  
  .avatar-icon {
    width: 20px;
    height: 20px;
    color: white;
  }
  
  .user-info {
    flex: 1;
    min-width: 0;
  }
  
  .user-role {
    font-weight: 600;
    color: #333;
    font-size: 0.9rem;
  }
  
  .user-username {
    font-size: 0.75rem;
    color: #999;
  }
  
  .login-form {
    margin-bottom: 1.5rem;
  }
  
  .login-form h3 {
    font-size: 0.95rem;
    color: #666;
    margin: 0 0 1rem 0;
    padding-bottom: 0.75rem;
    border-bottom: 2px solid #f0f0f0;
  }
  
  .error-message {
    background: #FFEBEE;
    color: #F44336;
    padding: 0.75rem;
    border-radius: 6px;
    margin-bottom: 1rem;
    font-size: 0.85rem;
    text-align: center;
  }
  
  .form-group {
    margin-bottom: 1rem;
  }
  
  .input-wrapper {
    display: flex;
    align-items: center;
    background: #f5f5f5;
    border-radius: 8px;
    padding: 0 1rem;
  }
  
  .input-icon {
    width: 20px;
    height: 20px;
    color: #999;
    margin-right: 0.75rem;
  }
  
  .input-wrapper input {
    flex: 1;
    padding: 0.85rem 0;
    border: none;
    background: transparent;
    font-size: 0.9rem;
    outline: none;
  }
  
  .toggle-password {
    background: transparent;
    border: none;
    cursor: pointer;
    padding: 0.5rem;
  }
  
  .toggle-icon {
    width: 18px;
    height: 18px;
    color: #999;
  }
  
  .login-btn {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.9rem;
    background: linear-gradient(135deg, #4CAF50 0%, #8BC34A 100%);
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 600;
    transition: all 0.3s;
  }
  
  .login-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(76, 175, 80, 0.3);
  }
  
  .btn-icon {
    width: 20px;
    height: 20px;
  }
  
  .login-footer {
    text-align: center;
  }
  
  .login-footer p {
    font-size: 0.8rem;
    color: #999;
    margin: 0;
  }
</style>
