// pages/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div class="text-center">
        <div class="mx-auto h-16 w-16 bg-primary-600 rounded-2xl flex items-center justify-center">
          <span class="text-3xl">🔒</span>
        </div>
        <h2 class="mt-6 text-3xl font-extrabold text-gray-900">
          安防工程商管理系统
        </h2>
        <p class="mt-2 text-sm text-gray-600">
          点位勘察与方案确认
        </p>
      </div>
      
      <div class="card">
        <form @submit.prevent="handleLogin" class="space-y-6">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">用户名</label>
            <input 
              v-model="username" 
              type="text" 
              class="input-field"
              placeholder="请输入用户名"
              required
            />
          </div>
          
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
            <input 
              v-model="password" 
              type="password" 
              class="input-field"
              placeholder="请输入密码"
              required
            />
          </div>

          <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">
            {{ error }}
          </div>
          
          <button 
            type="submit" 
            class="w-full btn-primary py-3 text-base"
            :disabled="loading"
          >
            {{ loading ? '登录中...' : '登录' }}
          </button>
        </form>

        <div class="mt-6 pt-6 border-t border-gray-100">
          <p class="text-xs text-gray-500 text-center mb-3">测试账号（密码均为 123456）</p>
          <div class="grid grid-cols-3 gap-2 text-xs text-center">
            <div class="bg-gray-50 p-2 rounded-lg">
              <div class="font-medium text-gray-700">pm</div>
              <div class="text-gray-500">项目经理</div>
            </div>
            <div class="bg-gray-50 p-2 rounded-lg">
              <div class="font-medium text-gray-700">leader</div>
              <div class="text-gray-500">施工队长</div>
            </div>
            <div class="bg-gray-50 p-2 rounded-lg">
              <div class="font-medium text-gray-700">engineer</div>
              <div class="text-gray-500">售后工程师</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const authStore = useAuthStore()
const username = ref('pm')
const password = ref('123456')
const error = ref('')
const loading = ref(false)

async function handleLogin() {
  try {
    error.value = ''
    loading.value = true
    await authStore.login(username.value, password.value)
    navigateTo('/')
  } catch (e: any) {
    error.value = e.message || '登录失败，请检查用户名和密码'
  } finally {
    loading.value = false
  }
}
</script>

// src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Car, Lock, User, AlertCircle } from 'lucide-react';
import { useAuthStore } from '../stores/authStore';
import { authApi } from '../api/client';
import { Button } from '../components/Common';

export const LoginPage: React.FC = () => {
  const navigate = useNavigate();
  const { login } = useAuthStore();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const result = await authApi.login(username, password);
      login(result.user, result.token);
      navigate('/');
    } catch (err: any) {
      setError(err.message || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
      <div className="max-w-md w-full">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-600 rounded-2xl mb-4">
            <Car className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900">驾校运营系统</h1>
          <p className="text-gray-600 mt-2">学时确认与费用结算平台</p>
        </div>

        <div className="bg-white rounded-2xl shadow-xl p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            {error && (
              <div className="flex items-center gap-2 p-3 bg-red-50 text-red-700 rounded-lg">
                <AlertCircle className="w-5 h-5 flex-shrink-0" />
                <span className="text-sm">{error}</span>
              </div>
            )}

            <div>
              <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-2">
                用户名
              </label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请输入用户名"
                  required
                />
              </div>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
                密码
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请输入密码"
                  required
                />
              </div>
            </div>

            <Button type="submit" loading={loading} className="w-full" size="lg">
              登录
            </Button>
          </form>

          <div className="mt-6 pt-6 border-t border-gray-200">
            <p className="text-center text-sm text-gray-600 mb-3">测试账号</p>
            <div className="grid grid-cols-3 gap-2 text-xs text-gray-500">
              <div className="text-center p-2 bg-gray-50 rounded">
                <p className="font-medium">advisor1</p>
                <p className="text-gray-400">招生顾问</p>
              </div>
              <div className="text-center p-2 bg-gray-50 rounded">
                <p className="font-medium">coach1</p>
                <p className="text-gray-400">教练</p>
              </div>
              <div className="text-center p-2 bg-gray-50 rounded">
                <p className="font-medium">examiner1</p>
                <p className="text-gray-400">考试专员</p>
              </div>
            </div>
            <p className="text-center text-xs text-gray-400 mt-2">密码：password123</p>
          </div>
        </div>
      </div>
    </div>
  );
};
