// src/app/login/page.tsx
'use client'

import { useAuthStore } from '@/lib/auth-store'
import { useRouter } from 'next/navigation'
import { UserRole, ROLE_LABELS } from '@/lib/types'
import { Stethoscope, ClipboardList, ShieldCheck } from 'lucide-react'
import { useEffect } from 'react'

const roleCards: { role: UserRole; icon: React.ReactNode; desc: string; color: string }[] = [
  {
    role: 'THERAPIST',
    icon: <Stethoscope size={36} />,
    desc: '查看排班、执行治疗、标记状态',
    color: 'from-blue-500 to-cyan-400',
  },
  {
    role: 'RECEPTION',
    icon: <ClipboardList size={36} />,
    desc: '签到办理、消课确认、催促退回补材料',
    color: 'from-accent-400 to-amber-400',
  },
  {
    role: 'DIRECTOR',
    icon: <ShieldCheck size={36} />,
    desc: '预警总览、全局排班、审批协调',
    color: 'from-navy-500 to-navy-300',
  },
]

const roleUserMap: Record<UserRole, { userId: string; userName: string }> = {
  THERAPIST: { userId: 'u1', userName: '张康复' },
  RECEPTION: { userId: 'u3', userName: '王前台' },
  DIRECTOR: { userId: 'u4', userName: '赵主任' },
}

const roleRedirect: Record<UserRole, string> = {
  THERAPIST: '/therapist/schedule',
  RECEPTION: '/reception/checkin',
  DIRECTOR: '/director/overview',
}

export default function LoginPage() {
  const { login, userRole } = useAuthStore()
  const router = useRouter()

  useEffect(() => {
    if (userRole) {
      router.push(roleRedirect[userRole])
    }
  }, [userRole, router])

  const handleLogin = (role: UserRole) => {
    const { userId, userName } = roleUserMap[role]
    login(userId, userName, role)
    router.push(roleRedirect[role])
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-navy-500 via-navy-400 to-navy-600 flex items-center justify-center p-8">
      <div className="w-full max-w-3xl">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-white tracking-wide">康复治疗中心</h1>
          <p className="text-navy-100 mt-3 text-lg">治疗排班与签到消课管理系统</p>
          <div className="w-20 h-1 bg-accent-400 mx-auto mt-4 rounded-full" />
        </div>

        <div className="grid grid-cols-3 gap-6">
          {roleCards.map((card) => (
            <button
              key={card.role}
              onClick={() => handleLogin(card.role)}
              className="group bg-white/10 backdrop-blur-sm rounded-2xl p-8 text-center hover:bg-white/20 transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl border border-white/10"
            >
              <div className={`w-20 h-20 mx-auto rounded-2xl bg-gradient-to-br ${card.color} flex items-center justify-center text-white mb-5 group-hover:scale-110 transition-transform duration-300 shadow-lg`}>
                {card.icon}
              </div>
              <h2 className="text-white text-lg font-bold mb-2">{ROLE_LABELS[card.role]}</h2>
              <p className="text-navy-100 text-sm leading-relaxed">{card.desc}</p>
            </button>
          ))}
        </div>

        <p className="text-center text-navy-200 text-xs mt-10">
          选择角色即可快速进入系统 · 简化登录模式
        </p>
      </div>
    </div>
  )
}

// src/pages/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { Sprout, Stethoscope, Crown, ArrowRight } from 'lucide-vue-next'

const router = useRouter()
const auth = useAuthStore()

const roles = [
  {
    key: '繁育员',
    icon: Sprout,
    desc: '负责仔猪转栏申请与确认',
    color: 'border-emerald-500/50 hover:shadow-emerald-500/20',
    iconColor: 'text-emerald-400',
    btnColor: 'bg-emerald-600 hover:bg-emerald-700',
  },
  {
    key: '兽医',
    icon: Stethoscope,
    desc: '负责健康评估与淘汰建议',
    color: 'border-blue-500/50 hover:shadow-blue-500/20',
    iconColor: 'text-blue-400',
    btnColor: 'bg-blue-600 hover:bg-blue-700',
  },
  {
    key: '场长',
    icon: Crown,
    desc: '负责审批淘汰与全局管理',
    color: 'border-amber-500/50 hover:shadow-amber-500/20',
    iconColor: 'text-amber-400',
    btnColor: 'bg-amber-600 hover:bg-amber-700',
  },
]

const names: Record<string, string> = {
  '繁育员': '',
  '兽医': '',
  '场长': '',
}

function handleEnter(roleKey: string) {
  const userName = names[roleKey].trim()
  if (!userName) return
  auth.login(roleKey, userName)
  router.push('/')
}
</script>

<template>
  <div class="min-h-screen bg-[#0f172a] flex items-center justify-center p-6">
    <div class="w-full max-w-3xl">
      <div class="text-center mb-10">
        <h1 class="text-3xl font-bold text-slate-100">仔猪转栏与淘汰评估</h1>
        <p class="text-slate-500 mt-2">选择您的角色进入系统</p>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div
          v-for="role in roles"
          :key="role.key"
          :class="[
            'card border-2 hover:shadow-lg transition-all duration-300 flex flex-col',
            role.color
          ]"
        >
          <div class="flex flex-col items-center pt-4 pb-3">
            <div class="w-14 h-14 rounded-full bg-slate-800 flex items-center justify-center mb-3">
              <component :is="role.icon" :size="28" :class="role.iconColor" />
            </div>
            <h3 class="text-lg font-semibold text-slate-100">{{ role.key }}</h3>
            <p class="text-xs text-slate-500 mt-1 text-center">{{ role.desc }}</p>
          </div>
          <div class="mt-auto pt-4 space-y-3">
            <input
              v-model="names[role.key]"
              type="text"
              placeholder="输入姓名"
              class="input-field text-sm"
              @keyup.enter="handleEnter(role.key)"
            />
            <button
              :disabled="!names[role.key].trim()"
              :class="[
                'w-full flex items-center justify-center gap-2 text-white font-medium py-2 rounded-lg transition-colors disabled:opacity-40 disabled:cursor-not-allowed',
                role.btnColor
              ]"
              @click="handleEnter(role.key)"
            >
              <span>进入</span>
              <ArrowRight :size="16" />
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
