// src/routes/students/+page.svelte
<script lang="ts">
	import Layout from '$lib/components/Layout.svelte';
	import ProgressBar from '$lib/components/ProgressBar.svelte';
	import { Search, Phone, Clock, Eye, User as UserIcon } from '@lucide/svelte';
	import type { Student, User } from '$lib/types';

	let { data } = $props<{
		data: {
			user: User;
			students: Student[];
		};
	}>();

	let searchQuery = $state('');

	const filteredStudents = $derived(
		data.students.filter((student: Student) =>
			student.name.toLowerCase().includes(searchQuery.toLowerCase())
		)
	);

	function getWarningClass(remaining: number, total: number): string {
		if (total === 0) return '';
		const percentage = (remaining / total) * 100;
		if (percentage < 20) return 'border-red-300 bg-red-50';
		if (percentage < 50) return 'border-orange-300 bg-orange-50';
		return 'border-gray-200 bg-white';
	}

	function getWarningText(remaining: number, total: number): string | null {
		if (total === 0) return null;
		const percentage = (remaining / total) * 100;
		if (percentage < 20) return '课时严重不足';
		if (percentage < 50) return '课时不足';
		return null;
	}
</script>

<Layout user={data.user}>
	<div class="space-y-6">
		<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
			<div>
				<h3 class="text-lg font-semibold text-gray-800">学生列表</h3>
				<p class="text-sm text-gray-500">共 {data.students.length} 名学生</p>
			</div>
			<div class="relative">
				<Search size={18} class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
				<input
					type="text"
					bind:value={searchQuery}
					placeholder="搜索学生姓名..."
					class="w-full sm:w-64 pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-transparent transition-all"
				/>
			</div>
		</div>

		{#if filteredStudents.length === 0}
			<div class="text-center py-16 bg-white rounded-xl border border-gray-200">
				<User size={48} class="mx-auto text-gray-300 mb-4" />
				<p class="text-gray-500">未找到匹配的学生</p>
			</div>
		{:else}
			<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
				{#each filteredStudents as student (student.id)}
					<div
						class="rounded-xl border p-5 shadow-sm transition-all duration-200 hover:shadow-md {getWarningClass(
							student.remainingHours,
							student.packageHours
						)}"
					>
						<div class="flex items-start justify-between mb-4">
							<div class="flex items-center gap-3">
								<div class="w-12 h-12 rounded-full bg-teal-100 flex items-center justify-center">
									<span class="text-teal-700 font-semibold text-lg">
										{student.name.charAt(0)}
									</span>
								</div>
								<div>
									<h4 class="font-semibold text-gray-800">{student.name}</h4>
									<div class="flex items-center gap-1.5 text-sm text-gray-500">
										<Phone size={14} />
										<span>{student.phone || '未填写'}</span>
									</div>
								</div>
							</div>
							{#if getWarningText(student.remainingHours, student.packageHours)}
								<span
									class="px-2 py-1 text-xs font-medium rounded-full {student.remainingHours /
										student.packageHours <
									0.2
										? 'bg-red-100 text-red-700'
										: 'bg-orange-100 text-orange-700'}"
								>
									{getWarningText(student.remainingHours, student.packageHours)}
								</span>
							{/if}
						</div>

						<div class="mb-4">
							<ProgressBar value={student.remainingHours} max={student.packageHours} />
						</div>

						<div class="flex items-center justify-between">
							<div class="flex items-center gap-1 text-sm text-gray-500">
								<Clock size={14} />
								<span>剩余 {student.remainingHours} 课时</span>
							</div>
							<a
								href={`/students/${student.id}`}
								class="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-teal-700 bg-teal-50 rounded-lg hover:bg-teal-100 transition-colors"
							>
								<Eye size={14} />
								查看详情
							</a>
						</div>
					</div>
				{/each}
			</div>
		{/if}
	</div>
</Layout>

// src/pages/Students.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Users as UsersIcon, Phone, CreditCard } from 'lucide-react';
import { Layout } from '../components/Layout';
import { Card, StatusBadge, LoadingSpinner, EmptyState, formatCurrency } from '../components/Common';
import { studentApi } from '../api/client';
import { useAuthStore } from '../stores/authStore';

export const StudentsPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const [students, setStudents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => {
    loadStudents();
  }, [search, statusFilter]);

  const loadStudents = async () => {
    try {
      setLoading(true);
      const params: any = {};
      if (search) params.search = search;
      if (statusFilter) params.status = statusFilter;
      if (user?.role === 'coach') params.coachId = user.id;

      const result = await studentApi.getAll(params);
      setStudents(result.students);
    } catch (err: any) {
      setError(err.message || '加载学员列表失败');
    } finally {
      setLoading(false);
    }
  };

  const getStatusLabel = (status: string) => {
    const statusMap: Record<string, string> = {
      enrolled: '报名中',
      studying: '学科学习',
      training: '练车中',
      examining: '约考中',
      graduated: '已拿证',
      dropped: '已退学',
    };
    return statusMap[status] || status;
  };

  return (
    <Layout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-gray-900">学员列表</h1>
        </div>

        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="搜索学员姓名或电话..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="">全部状态</option>
            <option value="enrolled">报名中</option>
            <option value="studying">学科学习</option>
            <option value="training">练车中</option>
            <option value="examining">约考中</option>
            <option value="graduated">已拿证</option>
            <option value="dropped">已退学</option>
          </select>
        </div>

        {loading ? (
          <LoadingSpinner />
        ) : error ? (
          <div className="text-center py-12 text-red-500">{error}</div>
        ) : students.length === 0 ? (
          <EmptyState message="暂无学员" icon={<UsersIcon className="w-12 h-12" />} />
        ) : (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {students.map((student) => (
              <Card
                key={student.id}
                onClick={() => navigate(`/students/${student.id}`)}
                className="p-4 cursor-pointer hover:shadow-md transition-shadow"
              >
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h3 className="font-semibold text-gray-900">{student.name}</h3>
                    <p className="text-sm text-gray-500 mt-1">报考类型：{student.examType}</p>
                  </div>
                  <StatusBadge status={student.status} />
                </div>

                <div className="space-y-2 text-sm text-gray-600">
                  <div className="flex items-center gap-2">
                    <Phone className="w-4 h-4" />
                    <span>{student.phone}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CreditCard className="w-4 h-4" />
                    <span>总费用：{formatCurrency(student.totalPaid)}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <UsersIcon className="w-4 h-4" />
                    <span>总学时：{student.totalHours}小时</span>
                  </div>
                </div>

                <div className="mt-3 pt-3 border-t border-gray-100 text-xs text-gray-400">
                  {student.advisor && <span>招生顾问：{student.advisor.realName}</span>}
                  {student.coach && <span className="ml-2">教练：{student.coach.realName}</span>}
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </Layout>
  );
};
