// src/pages/bookings/new.tsx
import { GetServerSideProps } from 'next';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import prisma from '@/lib/db';
import { requireAuth, serializeUser } from '@/lib/auth';
import Layout from '@/components/Layout';

const packageTypes = ['标准套餐', '豪华套餐', '高级套餐', '基础套餐'];

export default function NewBookingPage({ user }: { user: ReturnType<typeof serializeUser> }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    companyName: '',
    contactPerson: '',
    contactPhone: '',
    scheduledDate: '',
    expectedCount: 50,
    packageType: '标准套餐',
    pricePerPerson: 380,
    remark: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/bookings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        const data = await res.json();
        router.push(`/bookings/${data.id}`);
      } else {
        alert('创建失败');
      }
    } catch (error) {
      alert('网络错误');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout user={user} title="新建预约">
      <div className="max-w-3xl mx-auto">
      <div className="space-y-6">
        <div className="flex items-center space-x-4">
          <Link href="/" className="text-gray-500 hover:text-gray-700">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <h1 className="text-2xl font-bold text-gray-900">新建团检预约</h1>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  单位名称 *
                </label>
                <input
                  type="text"
                  value={formData.companyName}
                  onChange={(e) => setFormData({ ...formData, companyName: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入单位名称"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  联系人 *
                </label>
                <input
                  type="text"
                  value={formData.contactPerson}
                  onChange={(e) => setFormData({ ...formData, contactPerson: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入联系人姓名"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  联系电话 *
                </label>
                <input
                  type="tel"
                  value={formData.contactPhone}
                  onChange={(e) => setFormData({ ...formData, contactPhone: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  placeholder="请输入联系电话"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  预约日期 *
                </label>
                <input
                  type="date"
                  value={formData.scheduledDate}
                  onChange={(e) => setFormData({ ...formData, scheduledDate: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  预计人数 *
                </label>
                <input
                  type="number"
                  value={formData.expectedCount}
                  onChange={(e) => setFormData({ ...formData, expectedCount: parseInt(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  min="1"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  套餐类型
                </label>
                <select
                  value={formData.packageType}
                  onChange={(e) => setFormData({ ...formData, packageType: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                >
                  {packageTypes.map((type) => (
                    <option key={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  单价 (元/人)
                </label>
                <input
                  type="number"
                  value={formData.pricePerPerson}
                  onChange={(e) => setFormData({ ...formData, pricePerPerson: parseFloat(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  min="0"
                />
              </div>

              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  备注
                </label>
                <textarea
                  value={formData.remark}
                  onChange={(e) => setFormData({ ...formData, remark: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                  rows={3}
                  placeholder="请输入备注信息"
                />
              </div>
            </div>

            <div className="flex justify-end space-x-4 pt-4 border-t border-gray-100">
              <Link
                href="/"
                className="px-6 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition"
              >
                取消
              </Link>
              <button
                type="submit"
                disabled={loading}
                className="px-6 py-2 bg-blue-500 text-white font-medium rounded-lg hover:bg-blue-600 transition disabled:opacity-50"
              >
                {loading ? '创建中...' : '创建预约'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const authResult = await requireAuth(context);
  if ('redirect' in authResult) {
    return { redirect: authResult.redirect };
  }

  return {
    props: {
      user: serializeUser(authResult.user),
    },
  };
};

// src/routes/makeup/new/+page.svelte
<script lang="ts">
	import { Plus, ArrowLeft } from '@lucide/svelte';
	import Layout from '$lib/components/Layout.svelte';
	import type { Student, User } from '$lib/types';

	let { data } = $props<{
		data: {
			user: User;
			students: Student[];
			preselectedStudentId: string;
		};
	}>();

	let formState = $state({
		studentId: data.preselectedStudentId || '',
		originalCourseDate: '',
		originalCourseName: '',
		reason: ''
	});

	let submitting = $state(false);
</script>

<Layout user={data.user}>
	<div class="space-y-6">
		<div class="flex items-center gap-4">
			<a
				href="/makeup"
				class="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50"
			>
				<ArrowLeft size={18} />
				返回
			</a>
			<div class="flex items-center gap-3">
				<div class="rounded-lg bg-teal-100 p-2">
					<Plus class="h-6 w-6 text-teal-700" />
				</div>
				<div>
					<h1 class="text-xl font-bold text-gray-800">新增补课申请</h1>
					<p class="text-sm text-gray-500">填写学生补课申请信息</p>
				</div>
			</div>
		</div>

		<div class="rounded-lg border border-gray-200 bg-white p-6">
			<form method="POST" class="space-y-6">
				<div class="grid gap-6 md:grid-cols-2">
					<div>
						<label class="mb-1 block text-sm font-medium text-gray-700">
							学生 <span class="text-red-500">*</span>
						</label>
						<select
							name="studentId"
							bind:value={formState.studentId}
							required
							class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
						>
							<option value="" disabled>请选择学生</option>
							{#each data.students as student}
								<option value={student.id}>{student.name}</option>
							{/each}
						</select>
					</div>

					<div>
						<label class="mb-1 block text-sm font-medium text-gray-700">
							原课程日期 <span class="text-red-500">*</span>
						</label>
						<input
							type="date"
							name="originalCourseDate"
							bind:value={formState.originalCourseDate}
							required
							class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
						/>
					</div>

					<div class="md:col-span-2">
						<label class="mb-1 block text-sm font-medium text-gray-700">
							原课程名称 <span class="text-red-500">*</span>
						</label>
						<input
							type="text"
							name="originalCourseName"
							bind:value={formState.originalCourseName}
							placeholder="请输入原课程名称"
							required
							class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
						/>
					</div>

					<div class="md:col-span-2">
						<label class="mb-1 block text-sm font-medium text-gray-700">请假原因</label>
						<textarea
							name="reason"
							bind:value={formState.reason}
							rows={4}
							placeholder="请输入请假原因（选填）"
							class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
						></textarea>
					</div>
				</div>

				<div class="flex items-center justify-end gap-3 border-t border-gray-100 pt-6">
					<a
						href="/makeup"
						class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50"
					>
						取消
					</a>
					<button
						type="submit"
						disabled={submitting}
						class="inline-flex items-center gap-2 rounded-lg bg-teal-700 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-teal-800 disabled:cursor-not-allowed disabled:opacity-50"
					>
						<Plus size={18} />
						提交申请
					</button>
				</div>
			</form>
		</div>
	</div>
</Layout>
