// client/src/layout/Layout.vue
<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { roleLabels } from '@/utils/constants'
import type { User } from '@/types'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()

const currentRole = ref<User['role']>('service')

const menuItems = [
  { key: 'dashboard', icon: '📊', label: '工作台', path: '/dashboard' },
  { key: 'receptions', icon: '👥', label: '团体接待', path: '/receptions' },
  { key: 'guide-tasks', icon: '🍎', label: '向导任务', path: '/guide-tasks' },
  { key: 'warehouse', icon: '📦', label: '仓库交接', path: '/warehouse' },
  { key: 'audit-logs', icon: '📝', label: '操作日志', path: '/audit-logs' }
]

const roleOptions = [
  { value: 'service', label: '园区客服' },
  { value: 'guide', label: '采摘向导' },
  { value: 'warehouse', label: '仓库员' }
]

function changeRole(role: User['role']) {
  currentRole.value = role
  userStore.setRole(role)
}

function isActive(path: string) {
  return route.path.startsWith(path)
}

function navigate(path: string) {
  router.push(path)
}

const userName = computed(() => userStore.currentUser?.name || '用户')
</script>

<template>
  <div class="layout">
    <aside class="sidebar">
      <div class="logo">
        <span class="logo-icon">🍑</span>
        <span class="logo-text">观光果园</span>
      </div>
      <nav class="menu">
        <div
          v-for="item in menuItems"
          :key="item.key"
          class="menu-item"
          :class="{ active: isActive(item.path) }"
          @click="navigate(item.path)"
        >
          <span class="menu-icon">{{ item.icon }}</span>
          <span class="menu-label">{{ item.label }}</span>
        </div>
      </nav>
    </aside>

    <div class="main">
      <header class="header">
        <div class="header-left">
          <span class="breadcrumb">{{ route.meta.title || '首页' }}</span>
        </div>
        <div class="header-right">
          <div class="role-switch">
            <span class="role-label">当前身份：</span>
            <div class="role-options">
              <span
                v-for="opt in roleOptions"
                :key="opt.value"
                class="role-opt"
                :class="{ active: currentRole === opt.value }"
                @click="changeRole(opt.value as User['role'])"
              >
                {{ opt.label }}
              </span>
            </div>
          </div>
          <div class="user-info">
            <span class="user-avatar">{{ userName.charAt(0) }}</span>
            <span class="user-name">{{ userName }}</span>
          </div>
        </div>
      </header>

      <main class="content">
        <router-view v-slot="{ Component }">
          <component :is="Component" :key="route.fullPath" />
        </router-view>
      </main>
    </div>
  </div>
</template>

<style scoped>
.layout {
  display: flex;
  height: 100vh;
  overflow: hidden;
}

.sidebar {
  width: 220px;
  background: #001529;
  color: #fff;
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
}

.logo {
  height: 60px;
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 20px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.logo-icon {
  font-size: 24px;
}

.logo-text {
  font-size: 16px;
  font-weight: 600;
}

.menu {
  flex: 1;
  padding: 12px 0;
  overflow-y: auto;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 20px;
  cursor: pointer;
  color: rgba(255, 255, 255, 0.7);
  transition: all 0.2s;
}

.menu-item:hover {
  color: #fff;
  background: rgba(255, 255, 255, 0.08);
}

.menu-item.active {
  color: #fff;
  background: #1890ff;
}

.menu-icon {
  font-size: 16px;
}

.menu-label {
  font-size: 14px;
}

.main {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.header {
  height: 60px;
  background: #fff;
  border-bottom: 1px solid #f0f0f0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  flex-shrink: 0;
}

.header-left {
  font-size: 16px;
  font-weight: 500;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 24px;
}

.role-switch {
  display: flex;
  align-items: center;
  gap: 8px;
}

.role-label {
  font-size: 13px;
  color: #666;
}

.role-options {
  display: flex;
  gap: 4px;
}

.role-opt {
  padding: 4px 12px;
  border-radius: 4px;
  font-size: 12px;
  cursor: pointer;
  color: #666;
  border: 1px solid transparent;
  transition: all 0.2s;
}

.role-opt:hover {
  color: #1890ff;
}

.role-opt.active {
  background: #e6f7ff;
  color: #1890ff;
  border-color: #91d5ff;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 8px;
}

.user-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: #1890ff;
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  font-weight: 600;
}

.user-name {
  font-size: 14px;
  color: #333;
}

.content {
  flex: 1;
  overflow: auto;
  background: #f0f2f5;
}
</style>

// src/components/Layout.svelte
<script lang="ts">
  import { User, Home, BedDouble, ChefHat, ClipboardList, Settings, LogOut, ChevronDown } from 'lucide-svelte'

  export let navigate: (path: string) => void
  export let currentUser: any = null
  export let handleLogout: () => void

  const navItems = [
    { name: '首页', href: '/', icon: Home },
    { name: '住宿管理', href: '/rooms', icon: BedDouble },
    { name: '订单管理', href: '/orders', icon: ClipboardList },
    { name: '食材库存', href: '/inventory', icon: ChefHat },
    { name: '系统设置', href: '/settings', icon: Settings }
  ]

  const roleLabels: Record<string, string> = {
    boss: '老板',
    chef: '后厨',
    housekeeper: '客房阿姨',
    staff: '员工'
  }

  function handleNavClick(path: string) {
    navigate(path)
  }
</script>

<nav class="navbar">
  <div class="nav-brand">
    <span class="logo">🏡 农家乐管理系统</span>
  </div>
  <div class="nav-menu">
    {#each navItems as item}
      <a 
        href={item.href} 
        class="nav-item {window.location.pathname === item.href ? 'active' : ''}"
        on:click|preventDefault={() => handleNavClick(item.href)}
      >
        <component is={item.icon} class="nav-icon" />
        <span>{item.name}</span>
      </a>
    {/each}
  </div>
  <div class="nav-user">
    <div class="user-info">
      <span class="user-role">{roleLabels[currentUser?.role] || '员工'}</span>
      <span class="user-name">{currentUser?.username || 'guest'}</span>
    </div>
    <button class="logout-btn" on:click={handleLogout}>
      <LogOut class="logout-icon" />
    </button>
  </div>
</nav>

<main>
  <slot />
</main>

<style>
  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem 2rem;
    background: linear-gradient(135deg, #4CAF50 0%, #8BC34A 100%);
    color: white;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    position: sticky;
    top: 0;
    z-index: 100;
  }
  
  .nav-brand .logo {
    font-size: 1.5rem;
    font-weight: bold;
  }
  
  .nav-menu {
    display: flex;
    gap: 2rem;
  }
  
  .nav-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 1rem;
    border-radius: 8px;
    text-decoration: none;
    color: white;
    transition: all 0.3s;
  }
  
  .nav-item:hover, .nav-item.active {
    background: rgba(255,255,255,0.2);
  }
  
  .nav-icon {
    width: 20px;
    height: 20px;
  }
  
  .nav-user {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 0.5rem 1rem;
    background: rgba(255,255,255,0.15);
    border-radius: 20px;
  }
  
  .user-info {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
  }
  
  .user-role {
    font-size: 0.75rem;
    opacity: 0.8;
  }
  
  .user-name {
    font-weight: 600;
    font-size: 0.9rem;
  }
  
  .logout-btn {
    background: transparent;
    border: none;
    cursor: pointer;
    padding: 0.3rem;
    border-radius: 4px;
    transition: all 0.3s;
  }
  
  .logout-btn:hover {
    background: rgba(255,255,255,0.2);
  }
  
  .logout-icon {
    width: 18px;
    height: 18px;
    color: white;
  }
  
  main {
    min-height: calc(100vh - 72px);
    padding: 2rem;
  }
</style>
