// src/lib/components/StatCard.svelte
<script lang="ts">
	import type { Component } from 'svelte';

	let {
		icon,
		title,
		value,
		color = 'teal'
	}: {
		icon: Component;
		title: string;
		value: number | string;
		color?: 'teal' | 'amber' | 'blue' | 'rose';
	} = $props();

	const colorGradients: Record<string, string> = {
		teal: 'from-teal-600 to-teal-700',
		amber: 'from-amber-500 to-amber-600',
		blue: 'from-blue-500 to-blue-600',
		rose: 'from-rose-500 to-rose-600'
	};

	const colorBgLight: Record<string, string> = {
		teal: 'bg-teal-50',
		amber: 'bg-amber-50',
		blue: 'bg-blue-50',
		rose: 'bg-rose-50'
	};

	const colorText: Record<string, string> = {
		teal: 'text-teal-700',
		amber: 'text-amber-600',
		blue: 'text-blue-600',
		rose: 'text-rose-600'
	};
</script>

<div
	class="group relative overflow-hidden rounded-2xl bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
>
	<div
		class="absolute inset-x-0 top-0 h-1 bg-gradient-to-r {colorGradients[color]}"
	></div>

	<div class="flex items-start justify-between">
		<div>
			<p class="text-sm font-medium text-gray-500">{title}</p>
			<p
				class="mt-2 text-3xl font-bold text-gray-800 transition-transform duration-300 group-hover:scale-105"
			>
				{value}
			</p>
		</div>

		<div
			class="flex h-12 w-12 items-center justify-center rounded-xl {colorBgLight[color]} transition-all duration-300 group-hover:scale-110 group-hover:rotate-3"
		>
			<svelte:component this={icon} size={24} class={colorText[color]} />
		</div>
	</div>

	<div
		class="absolute -bottom-10 -right-10 h-32 w-32 rounded-full opacity-0 transition-opacity duration-300 group-hover:opacity-10 {colorBgLight[color]}"
	></div>
</div>

// src/components/StatCard.tsx
import type { ReactNode } from 'react';

interface StatCardProps {
  title: string;
  value: number | string;
  icon: ReactNode;
  color: 'primary' | 'warning' | 'success' | 'danger' | 'neutral';
  trend?: {
    value: number;
    isUp: boolean;
  };
}

export function StatCard({ title, value, icon, color, trend }: StatCardProps) {
  const colorStyles = {
    primary: 'bg-primary-50 text-primary-600',
    warning: 'bg-warning-50 text-warning-500',
    success: 'bg-success-50 text-success-600',
    danger: 'bg-danger-50 text-danger-600',
    neutral: 'bg-neutral-100 text-neutral-600',
  };

  const bgColorStyles = {
    primary: 'bg-primary-700',
    warning: 'bg-warning-500',
    success: 'bg-success-500',
    danger: 'bg-danger-500',
    neutral: 'bg-neutral-600',
  };

  return (
    <div className="card p-5 hover:shadow-cardHover transition-all duration-300 group">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <p className="text-sm text-neutral-500 mb-1">{title}</p>
          <p className="text-2xl font-bold text-neutral-800 font-mono-cn">{value}</p>
          {trend && (
            <p
              className={`text-xs mt-1 flex items-center gap-1 ${
                trend.isUp ? 'text-success-600' : 'text-danger-600'
              }`}
            >
              {trend.isUp ? '↑' : '↓'} {Math.abs(trend.value)}% 较昨日
            </p>
          )}
        </div>
        <div
          className={`w-12 h-12 rounded-lg flex items-center justify-center ${colorStyles[color]} group-hover:scale-110 transition-transform duration-300`}
        >
          {icon}
        </div>
      </div>
      <div className={`h-1 w-full rounded-full mt-4 ${bgColorStyles[color]} opacity-20`} />
    </div>
  );
}
