// src/components/StatusTimeline.tsx
import type { StatusLog, FollowUpStatus } from '@/types'
import { STATUS_LABELS, ROLE_LABELS } from '@/types'
import { formatTimeAgo, getStatusColor } from '@/utils/statusEngine'

const dotColors: Record<FollowUpStatus, string> = {
  pending: 'bg-gray-400',
  in_progress: 'bg-blue-500',
  pending_review: 'bg-amber-500',
  completed: 'bg-emerald-500',
  warned: 'bg-red-500',
  confirmed: 'bg-teal-500',
}

interface StatusTimelineProps {
  logs: StatusLog[]
}

export default function StatusTimeline({ logs }: StatusTimelineProps) {
  const sorted = [...logs].sort(
    (a, b) => new Date(b.operatedAt).getTime() - new Date(a.operatedAt).getTime()
  )

  return (
    <div className="relative pl-6">
      {sorted.map((log, idx) => {
        const isLast = idx === sorted.length - 1
        return (
          <div key={log.id} className="relative pb-6 last:pb-0">
            <div
              className={`absolute left-[-1.375rem] top-1 h-3 w-3 rounded-full ${dotColors[log.toStatus]} ring-2 ring-white`}
            />
            {!isLast && (
              <div className="absolute left-[-0.875rem] top-4 bottom-0 w-px bg-slate-200" />
            )}
            <div className="ml-2">
              {log.fromStatus && log.fromStatus === log.toStatus ? (
                <div className="flex items-center gap-2 text-sm">
                  <span
                    className="inline-flex items-center gap-1.5 font-medium text-blue-600"
                  >
                    <span className={`inline-block h-1.5 w-1.5 rounded-full ${getStatusColor(log.toStatus)}`} />
                    {STATUS_LABELS[log.toStatus]}
                  </span>
                  <span className="text-slate-400 text-xs">· 负责人变更</span>
                </div>
              ) : (
                <div className="flex items-center gap-2 text-sm">
                  <span className="text-slate-500">
                    {log.fromStatus ? STATUS_LABELS[log.fromStatus] : '—'}
                  </span>
                  <span className="text-slate-400">→</span>
                  <span
                    className={`inline-flex items-center gap-1.5 font-medium ${
                      log.toStatus === 'warned'
                        ? 'text-red-600'
                        : log.toStatus === 'completed'
                        ? 'text-emerald-600'
                        : log.toStatus === 'confirmed'
                        ? 'text-teal-600'
                        : 'text-slate-800'
                    }`}
                  >
                    <span className={`inline-block h-1.5 w-1.5 rounded-full ${getStatusColor(log.toStatus)}`} />
                    {STATUS_LABELS[log.toStatus]}
                  </span>
                </div>
              )}
              <div className="mt-1 flex items-center gap-2 text-xs text-slate-400">
                <span>
                  {log.operatorName}（{ROLE_LABELS[log.operatorRole]}）
                </span>
                <span>·</span>
                <span>{formatTimeAgo(log.operatedAt)}</span>
              </div>
              {log.remark && (
                <p className="mt-1 text-xs text-slate-500">{log.remark}</p>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}

// src/components/StatusTimeline.vue
<script setup lang="ts">
import type { StatusLog } from '../types/index.js';
import { InspectionStatusLabel } from '../types/index.js';
import { CheckCircle, Clock, AlertCircle, Send, Wrench, Eye, XCircle } from 'lucide-vue-next';

interface Props {
  logs: StatusLog[];
}

defineProps<Props>();

const statusIcons: Record<string, any> = {
  pending_review: AlertCircle,
  dispatched: Send,
  in_progress: Wrench,
  completed: CheckCircle,
  pending_review_after: Eye,
  passed: CheckCircle,
  rejected: XCircle
};

const statusColors: Record<string, string> = {
  pending_review: 'bg-gray-400',
  dispatched: 'bg-blue-500',
  in_progress: 'bg-yellow-500',
  completed: 'bg-purple-500',
  pending_review_after: 'bg-orange-500',
  passed: 'bg-green-500',
  rejected: 'bg-red-500'
};
</script>

<template>
  <div class="relative">
    <div class="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-200" />
    <div class="space-y-6">
      <div
        v-for="(log, index) in logs"
        :key="log.id"
        class="relative pl-10 pb-6 last:pb-0"
        :style="{ animationDelay: `${index * 0.1}s` }"
      >
        <div
          :class="[
            'absolute left-0 w-8 h-8 rounded-full flex items-center justify-center ring-4 ring-white',
            statusColors[log.toStatus] || 'bg-gray-400'
          ]"
        >
          <component
            :is="statusIcons[log.toStatus] || Clock"
            class="w-4 h-4 text-white"
          />
        </div>
        <div class="bg-white rounded-lg p-4 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
          <div class="flex items-center justify-between mb-2">
            <span class="font-medium text-gray-800">
              {{ InspectionStatusLabel[log.toStatus] }}
            </span>
            <span class="text-xs text-gray-500">{{ log.timestamp }}</span>
          </div>
          <p class="text-sm text-gray-600 mb-2">{{ log.remark }}</p>
          <p class="text-xs text-gray-400">操作人：{{ log.operatorName }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
