// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { currentUser } from '$lib/stores/user';
  
  let username = '';
  let password = '';
  let selectedRole = 'EXAM_OFFICER';
  let error = '';
  let loading = false;
  
  const roles = [
    { value: 'EXAM_OFFICER', label: '考务专员', description: '负责监考安排、处理异常情况' },
    { value: 'INVIGILATOR', label: '监考老师', description: '执行监考任务、确认签到' },
    { value: 'TECH_SUPPORT', label: '技术支持', description: '处理系统异常、数据维护' }
  ];
  
  async function handleLogin() {
    error = '';
    loading = true;
    
    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password, role: selectedRole })
      });
      
      const data = await response.json();
      
      if (response.ok) {
        localStorage.setItem('user', JSON.stringify(data.user));
        currentUser.set(data.user);
        goto('/');
      } else {
        error = data.error || '登录失败';
      }
    } catch (e) {
      error = '网络错误，请稍后重试';
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-900 to-primary-700">
  <div class="w-full max-w-md">
    <div class="bg-white rounded-lg shadow-xl p-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-primary mb-2">考务中心</h1>
        <p class="text-gray-600">监考安排与签到确认系统</p>
      </div>
      
      <form onsubmit={(e) => { e.preventDefault(); handleLogin(); }} class="space-y-6">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">用户名</label>
          <input 
            type="text" 
            bind:value={username}
            class="input"
            placeholder="请输入用户名"
            required
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
          <input 
            type="password" 
            bind:value={password}
            class="input"
            placeholder="请输入密码"
            required
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">登录角色</label>
          <div class="space-y-2">
            {#each roles as role}
              <button 
                type="button"
                onclick={() => selectedRole = role.value}
                class="w-full p-4 rounded-md border-2 transition-all text-left {selectedRole === role.value ? 'border-primary bg-primary-50' : 'border-gray-200 hover:border-gray-300'}"
              >
                <div class="font-medium {selectedRole === role.value ? 'text-primary' : 'text-gray-800'}">{role.label}</div>
                <div class="text-sm text-gray-500 mt-1">{role.description}</div>
              </button>
            {/each}
          </div>
        </div>
        
        {#if error}
          <div class="text-danger text-sm text-center">{error}</div>
        {/if}
        
        <button 
          type="submit" 
          disabled={loading}
          class="w-full btn btn-primary py-3 {loading ? 'opacity-50 cursor-not-allowed' : ''}"
        >
          {loading ? '登录中...' : '登录'}
        </button>
      </form>
      
      <div class="mt-6 text-center text-sm text-gray-500">
        <p>测试账号：任意用户名 / 密码：123456</p>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'
import { authApi } from '@/services/api'
import { AlertCircle, Baby } from 'lucide-react'

export default function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()
  const { login } = useAuthStore()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const response = await authApi.login(username, password)
      if (response.success && response.data) {
        login(response.data.user, response.data.token)
        navigate('/')
      } else {
        setError(response.error?.message || '登录失败')
      }
    } catch (err: any) {
      setError(err.response?.data?.error?.message || '网络错误，请重试')
    } finally {
      setLoading(false)
    }
  }

  const demoAccounts = [
    { username: 'clerk001', password: '123456', role: '店员' },
    { username: 'manager001', password: '123456', role: '店长' },
    { username: 'buyer001', password: '123456', role: '采购' },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-accent-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <div className="flex items-center justify-center mb-8">
            <div className="w-16 h-16 bg-primary rounded-2xl flex items-center justify-center">
              <Baby size={32} className="text-white" />
            </div>
          </div>

          <h1 className="text-2xl font-bold text-center text-gray-800 mb-2">
            母婴零售店促销券系统
          </h1>
          <p className="text-center text-gray-500 mb-8">
            请登录您的账号
          </p>

          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg flex items-center text-red-700 text-sm">
              <AlertCircle size={18} className="mr-2 flex-shrink-0" />
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                用户名
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                placeholder="请输入用户名"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                密码
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                placeholder="请输入密码"
                required
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full btn btn-primary py-3 text-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-sm text-gray-500 text-center mb-4">测试账号</p>
            <div className="space-y-2">
              {demoAccounts.map((account) => (
                <button
                  key={account.username}
                  onClick={() => {
                    setUsername(account.username)
                    setPassword(account.password)
                  }}
                  className="w-full p-3 bg-gray-50 hover:bg-gray-100 rounded-lg transition-colors text-left"
                >
                  <div className="flex justify-between items-center">
                    <div>
                      <span className="text-sm font-medium text-gray-800">
                        {account.username}
                      </span>
                      <span className="text-xs text-gray-500 ml-2">
                        (密码: {account.password})
                      </span>
                    </div>
                    <span className="text-xs bg-primary-100 text-primary px-2 py-1 rounded">
                      {account.role}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
