// coffee-roastery/src/routes/login/+page.svelte
<script lang="ts">
	let username = $state('');
	let password = $state('');
	let error = $state('');
	let loading = $state(false);

	async function handleLogin() {
		loading = true;
		error = '';
		try {
			const res = await fetch('/api/auth/login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ username, password })
			});
			if (res.ok) {
				window.location.href = '/';
			} else {
				const data = await res.json();
				error = data.error || '登录失败';
			}
		} catch {
			error = '网络错误';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen bg-stone-100 flex items-center justify-center">
	<div class="bg-white rounded-lg shadow-md p-8 w-full max-w-md">
		<h1 class="text-2xl font-bold text-stone-800 mb-1">咖啡烘焙厂</h1>
		<p class="text-stone-500 text-sm mb-6">生豆入库与烘焙计划系统</p>

		{#if error}
			<div class="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded text-sm mb-4">{error}</div>
		{/if}

		<form onsubmit={(e) => { e.preventDefault(); handleLogin(); }}>
			<div class="mb-4">
				<label class="block text-sm font-medium text-stone-700 mb-1">用户名</label>
				<input type="text" bind:value={username} class="w-full border border-stone-300 rounded px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-stone-400" placeholder="请输入用户名" />
			</div>
			<div class="mb-6">
				<label class="block text-sm font-medium text-stone-700 mb-1">密码</label>
				<input type="password" bind:value={password} class="w-full border border-stone-300 rounded px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-stone-400" placeholder="请输入密码" />
			</div>
			<button type="submit" disabled={loading} class="w-full bg-stone-800 text-white py-2 rounded text-sm font-medium hover:bg-stone-700 disabled:opacity-50 transition-colors">
				{loading ? '登录中...' : '登录'}
			</button>
		</form>

		<div class="mt-6 pt-4 border-t border-stone-200">
			<p class="text-xs text-stone-400 mb-2">演示账号：</p>
			<div class="space-y-1 text-xs text-stone-500">
				<p>烘焙师：roaster_zhang / 123456</p>
				<p>杯测员：cupper_li / 123456</p>
				<p>渠道客服：cs_wang / 123456</p>
			</div>
		</div>
	</div>
</div>

// client/src/components/Login.tsx
import { useState } from 'react';
import { User, Lock, LogIn } from 'lucide-react';
import { authAPI } from '../api';
import { User as UserType } from '../types';

interface LoginProps {
  onLogin: (user: UserType) => void;
}

export function Login({ onLogin }: LoginProps) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    
    try {
      const response = await authAPI.login(username, password);
      if (response.success) {
        onLogin(response.user);
      } else {
        setError(response.message);
      }
    } catch {
      setError('登录失败，请稍后重试');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-8">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-primary-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <LogIn className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-2xl font-bold text-gray-800">叉车维保管理系统</h1>
          <p className="text-gray-500 mt-2">请登录系统</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">用户名</label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition"
                placeholder="请输入用户名"
              />
            </div>
          </div>

          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">密码</label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition"
                placeholder="请输入密码"
              />
            </div>
          </div>

          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
              {error}
            </div>
          )}

          <button
            type="submit"
            className="w-full bg-primary-500 hover:bg-primary-600 text-white font-medium py-3 px-4 rounded-lg transition-colors"
          >
            登录
          </button>
        </form>

        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <p className="text-sm text-gray-600">测试账号：</p>
          <div className="mt-2 space-y-1 text-sm">
            <p><span className="font-medium">维保主管：</span>manager / 123456</p>
            <p><span className="font-medium">现场技师：</span>liming / 123456</p>
            <p><span className="font-medium">仓管：</span>warehouse / 123456</p>
          </div>
        </div>
      </div>
    </div>
  );
}
