// src/components/StatusBadge.vue
<template>
  <span
    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium font-heading"
    :style="badgeStyle"
  >
    {{ label }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { STATUS_LABELS, STATUS_COLORS } from '@/types'
import type { Registration } from '@/types'

const props = defineProps<{
  status: Registration['status']
}>()

const label = computed(() => STATUS_LABELS[props.status] ?? props.status)
const color = computed(() => STATUS_COLORS[props.status] ?? '#8B949E')

const badgeStyle = computed(() => ({
  backgroundColor: `${color.value}20`,
  color: color.value,
  border: `1px solid ${color.value}40`,
}))
</script>

// client/src/components/StatusBadge.tsx
import { STATUS_LABELS, STATUS_COLORS } from '../types';

export default function StatusBadge({ status }: { status: string }) {
  const label = STATUS_LABELS[status] || status;
  const color = STATUS_COLORS[status] || 'bg-gray-100 text-gray-700';
  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {label}
    </span>
  );
}
