// components/StatusBadge.vue
<template>
  <span
    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
    :class="getStatusColor(status)"
  >
    {{ getStatusText(status) }}
  </span>
</template>

<script setup lang="ts">
import { useFormat } from '../composables/useFormat'
import type { OrderStatus, CustomsStatus } from '../types'

interface Props {
  status: OrderStatus | CustomsStatus
  type?: 'order' | 'customs'
}

const props = withDefaults(defineProps<Props>(), {
  type: 'order'
})

const { getStatusText, getStatusColor } = useFormat()
</script>

// client/src/components/StatusBadge.tsx
import { STATUS_LABELS, STATUS_COLORS } from '../types';

export default function StatusBadge({ status }: { status: string }) {
  const label = STATUS_LABELS[status] || status;
  const color = STATUS_COLORS[status] || 'bg-gray-100 text-gray-700';
  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {label}
    </span>
  );
}
