// src/components/AppLayout.tsx
import { useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useRoleStore } from '@/stores/roleStore'
import { useScheduleStore } from '@/stores/scheduleStore'
import { useSettlementStore } from '@/stores/settlementStore'
import { useExceptionStore } from '@/stores/exceptionStore'
import { ROLE_CONFIGS } from '@/types'
import {
  LayoutDashboard,
  CalendarClock,
  Receipt,
  AlertTriangle,
  ScrollText,
  ChevronLeft,
  ChevronRight,
  Users,
  Shield,
} from 'lucide-react'

const navItems = [
  { path: '/', label: '工作台', icon: LayoutDashboard },
  { path: '/schedule', label: '车辆排班', icon: CalendarClock },
  { path: '/settlement', label: '用车结算', icon: Receipt },
  { path: '/exception', label: '异常说明', icon: AlertTriangle },
  { path: '/logs', label: '操作日志', icon: ScrollText },
]

const ROLE_DESCRIPTIONS: Record<string, string> = {
  dispatcher: '可创建排班、补录、重新提交结算',
  fleet_manager: '可确认出车/回车、标记异常',
  finance: '可审核结算、通过或驳回',
  supervisor: '可查看全量数据、风险看板、操作日志',
}

export default function AppLayout({ children }: { children: React.ReactNode }) {
  const [collapsed, setCollapsed] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()
  const { currentRole, switchRole, hasPermission } = useRoleStore()

  const pendingSchedules = useScheduleStore((s) => s.schedules.filter((sc) => sc.status === 'PENDING').length)
  const pendingSettlements = useSettlementStore((s) => s.settlements.filter((st) => st.status === 'PENDING_REVIEW').length)
  const rejectedSettlements = useSettlementStore((s) => s.settlements.filter((st) => st.status === 'REJECTED').length)
  const pendingExceptions = useExceptionStore((s) => s.exceptions.filter((e) => e.status === 'pending').length)

  const navBadges: Record<string, number> = {
    '/schedule': pendingSchedules,
    '/settlement': pendingSettlements + rejectedSettlements,
    '/exception': pendingExceptions,
  }

  const currentRoleConfig = ROLE_CONFIGS.find((c) => c.name === currentRole)

  return (
    <div className="flex h-screen bg-[#ecf0f5]">
      <aside
        className={`${collapsed ? 'w-16' : 'w-52'} bg-[#1a2332] flex flex-col transition-all duration-200 flex-shrink-0`}
      >
        <div className="h-14 flex items-center justify-center border-b border-white/10">
          {!collapsed && (
            <span className="text-white font-bold text-sm tracking-wide">
              车辆排班结算
            </span>
          )}
          {collapsed && <CalendarClock className="w-5 h-5 text-amber-400" />}
        </div>

        <nav className="flex-1 py-2">
          {navItems.map((item) => {
            const isActive =
              item.path === '/'
                ? location.pathname === '/'
                : location.pathname.startsWith(item.path)
            const Icon = item.icon
            const badge = navBadges[item.path] || 0
            return (
              <button
                key={item.path}
                onClick={() => navigate(item.path)}
                className={`w-full flex items-center gap-3 px-4 py-3 text-sm transition-colors relative ${
                  isActive
                    ? 'bg-white/10 text-amber-400 border-r-2 border-amber-400'
                    : 'text-gray-400 hover:bg-white/5 hover:text-gray-200'
                }`}
              >
                <Icon className="w-5 h-5 flex-shrink-0" />
                {!collapsed && (
                  <>
                    <span>{item.label}</span>
                    {badge > 0 && (
                      <span className="ml-auto bg-red-500 text-white text-xs px-1.5 py-0.5 rounded-full min-w-[18px] text-center leading-tight">
                        {badge}
                      </span>
                    )}
                  </>
                )}
                {collapsed && badge > 0 && (
                  <span className="absolute top-2 right-2 bg-red-500 text-white text-xs w-4 h-4 rounded-full flex items-center justify-center leading-none">
                    {badge > 9 ? '9+' : badge}
                  </span>
                )}
              </button>
            )
          })}
        </nav>

        <button
          onClick={() => setCollapsed(!collapsed)}
          className="h-10 flex items-center justify-center text-gray-500 hover:text-gray-300 border-t border-white/10"
        >
          {collapsed ? <ChevronRight className="w-4 h-4" /> : <ChevronLeft className="w-4 h-4" />}
        </button>
      </aside>

      <div className="flex-1 flex flex-col min-w-0">
        <header className="h-14 bg-white border-b border-gray-200 flex items-center justify-between px-6 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Shield size={14} className="text-[#e67e22]" />
              <span className="text-sm text-gray-500">当前角色</span>
            </div>
            <select
              value={currentRole}
              onChange={(e) => switchRole(e.target.value as typeof currentRole)}
              className="text-sm font-medium text-[#1a2332] bg-gray-50 border border-gray-200 rounded-md px-3 py-1.5 focus:outline-none focus:ring-2 focus:ring-[#e67e22]/30 focus:border-[#e67e22] transition-colors"
            >
              {ROLE_CONFIGS.map((r) => (
                <option key={r.name} value={r.name}>
                  {r.label}
                </option>
              ))}
            </select>
            <span className="text-xs text-gray-400 max-w-[280px] truncate">
              {ROLE_DESCRIPTIONS[currentRole] || ''}
            </span>
          </div>
          <div className="flex items-center gap-4">
            {(rejectedSettlements > 0) && (
              <div
                onClick={() => navigate('/settlement')}
                className="flex items-center gap-1.5 text-xs text-red-600 bg-red-50 border border-red-100 rounded-md px-2.5 py-1 cursor-pointer hover:bg-red-100 transition-colors"
              >
                <AlertTriangle size={12} />
                <span>{rejectedSettlements}笔驳回待处理</span>
              </div>
            )}
            <div className="text-xs text-gray-400">
              旅游地接社 · 车辆排班与用车结算
            </div>
          </div>
        </header>

        <main className="flex-1 overflow-auto p-6">{children}</main>
      </div>
    </div>
  )
}

// src/layouts/AppLayout.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  LayoutDashboard, ClipboardList, MapPin, RefreshCcw, History,
  Cable, ChevronDown, Search, Bell, User, LogOut, UserCog
} from 'lucide-vue-next'
import { useDataStore } from '@/stores/data'
import UiBadge from '@/components/ui/UiBadge.vue'
import UiButton from '@/components/ui/UiButton.vue'

const route = useRoute()
const router = useRouter()
const store = useDataStore()

const currentProjectId = ref<string>('')
const searchText = ref('')

const navItems = [
  { path: '/', name: '仪表盘', icon: LayoutDashboard },
  { path: '/requisitions', name: '领料管理', icon: ClipboardList, badge: () => store.pendingRequisitions.length },
  { path: '/checkin', name: '现场打卡', icon: MapPin },
  { path: '/returns', name: '补领与退回', icon: RefreshCcw, badge: () => store.pendingReturns.length },
  { path: '/history', name: '历史记录', icon: History }
]

const breadcrumb = computed(() => (route.meta.title as string) || '仪表盘')
const projectOptions = computed(() => store.projects.filter(p => p.status === 'active'))

function navigate(path: string) {
  router.push(path)
}

function onProjectChange(e: Event) {
  const id = (e.target as HTMLSelectElement).value
  currentProjectId.value = id
  store.loadAll(id)
}

onMounted(async () => {
  await store.loadAll()
  if (projectOptions.value.length > 0 && !currentProjectId.value) {
    currentProjectId.value = projectOptions.value[0].id
  }
})
</script>

<template>
  <div class="min-h-screen flex bg-[#FAFAFA]">
    <aside class="fixed left-0 top-0 bottom-0 w-[240px] flex flex-col text-white shadow-xl z-20"
           style="background: linear-gradient(180deg, #1E3A8A 0%, #1E40AF 100%);">
      <div class="px-5 py-5 border-b border-white/10 flex items-center gap-3">
        <div class="w-10 h-10 rounded-lg bg-white/15 flex items-center justify-center shrink-0">
          <Cable class="w-5 h-5 text-white" />
        </div>
        <div class="min-w-0">
          <h1 class="font-serif-sc font-bold text-[15px] leading-tight tracking-wide truncate">弱电施工</h1>
          <h2 class="font-serif-sc font-semibold text-[13px] text-blue-200 leading-tight tracking-wide truncate">线缆管理系统</h2>
        </div>
      </div>

      <nav class="flex-1 py-3 px-3 space-y-1 overflow-y-auto scrollbar-thin">
        <button
          v-for="item in navItems"
          :key="item.path"
          type="button"
          @click="navigate(item.path)"
          class="w-full relative flex items-center gap-3 px-3 py-2.5 text-sm rounded-md transition-all duration-200 group"
          :class="route.path === item.path
            ? 'bg-white/15 text-white font-medium'
            : 'text-blue-100 hover:bg-white/8 hover:text-white'"
        >
          <div
            v-if="route.path === item.path"
            class="absolute left-0 top-1.5 bottom-1.5 w-1 rounded-r bg-white"
          />
          <component :is="item.icon" class="w-[18px] h-[18px] shrink-0" />
          <span class="flex-1 text-left">{{ item.name }}</span>
          <UiBadge
            v-if="item.badge && item.badge() > 0"
            variant="red"
            size="sm"
            class="!bg-red-500 !text-white !border-red-400"
          >
            {{ item.badge() }}
          </UiBadge>
        </button>
      </nav>

      <div class="px-3 py-3 border-t border-white/10">
        <div class="bg-white/10 rounded-lg p-3">
          <div class="flex items-center gap-2.5 mb-2.5">
            <div class="w-9 h-9 rounded-full bg-white/20 flex items-center justify-center shrink-0">
              <User class="w-4.5 h-4.5" />
            </div>
            <div class="min-w-0 flex-1">
              <p class="text-sm font-semibold truncate">王建国</p>
              <p class="text-[11px] text-blue-200 truncate">项目负责人</p>
            </div>
          </div>
          <UiButton
            variant="ghost"
            size="sm"
            class="w-full !bg-white/10 !text-white hover:!bg-white/20 !justify-start !px-2"
          >
            <template #icon><UserCog class="w-3.5 h-3.5" /></template>
            切换角色
          </UiButton>
        </div>
      </div>
    </aside>

    <div class="ml-[240px] flex-1 flex flex-col min-w-0">
      <header class="sticky top-0 z-10 bg-white border-b border-gray-200 shadow-sm">
        <div class="px-6 py-3 flex items-center gap-4">
          <div class="flex items-center gap-1.5 text-sm text-gray-500 shrink-0">
            <LayoutDashboard class="w-4 h-4" />
            <ChevronDown class="w-3.5 h-3.5 -rotate-90" />
            <span class="text-gray-900 font-medium">{{ breadcrumb }}</span>
          </div>

          <div class="flex-1 max-w-xs">
            <select
              :value="currentProjectId"
              @change="onProjectChange"
              class="w-full px-3 py-2 text-sm bg-gray-50 border border-gray-200 rounded-md text-gray-900 focus:outline-none focus:border-[#1E40AF] focus:ring-2 focus:ring-[#1E40AF]/15 appearance-none cursor-pointer"
            >
              <option value="" disabled>选择项目...</option>
              <option v-for="p in projectOptions" :key="p.id" :value="p.id">{{ p.name }}</option>
            </select>
          </div>

          <div class="flex-1 max-w-sm relative">
            <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              v-model="searchText"
              type="text"
              placeholder="搜索单据、线缆、班组..."
              class="w-full pl-9 pr-3 py-2 text-sm bg-gray-50 border border-gray-200 rounded-md text-gray-900 placeholder:text-gray-400 focus:outline-none focus:border-[#1E40AF] focus:ring-2 focus:ring-[#1E40AF]/15"
            />
          </div>

          <div class="flex items-center gap-1 ml-auto shrink-0">
            <button type="button" class="relative p-2 rounded-md text-gray-500 hover:bg-gray-100 transition-colors">
              <Bell class="w-5 h-5" />
              <span class="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-red-500 ring-2 ring-white" />
            </button>
            <div class="w-px h-6 bg-gray-200 mx-1" />
            <div class="flex items-center gap-2 pl-1">
              <div class="w-8 h-8 rounded-full bg-[#1E40AF]/10 flex items-center justify-center text-[#1E40AF] font-semibold text-sm">王</div>
            </div>
          </div>
        </div>
      </header>

      <main class="flex-1">
        <div class="pt-6 px-6 pb-12">
          <router-view v-slot="{ Component }">
            <transition name="fade-slide" mode="out-in">
              <div class="fade-slide">
                <component :is="Component" />
              </div>
            </transition>
          </router-view>
        </div>
      </main>
    </div>
  </div>
</template>
