// src/components/layout/Layout.tsx
import { NavLink, useLocation, useNavigate } from 'react-router-dom';
import { 
  LayoutDashboard, 
  PlusCircle, 
  Download, 
  Users,
  Menu,
  X,
  RefreshCw,
  ShoppingBag
} from 'lucide-react';
import { useState } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { ROLE_LABELS } from '@/types';
import type { Role } from '@/types';

interface LayoutProps {
  children: React.ReactNode;
}

export function Layout({ children }: LayoutProps) {
  const location = useLocation();
  const navigate = useNavigate();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const currentRole = useAppStore(state => state.currentRole);
  const setCurrentRole = useAppStore(state => state.setCurrentRole);
  const { promotions, getPendingPromotions } = useAppStore();

  const pendingCount = getPendingPromotions().length;
  const salesReviewCount = promotions.filter(p => 
    p.status === 'salesPending' || (p.status === 'active' && !p.salesData)
  ).length;

  const navItems = [
    { path: '/', label: '工作台', icon: LayoutDashboard, badge: pendingCount > 0 ? pendingCount : null },
    { path: '/promotion/new', label: '新建促销', icon: PlusCircle, badge: null },
    { path: '/io', label: '导入导出', icon: Download, badge: null },
  ];

  const roles: Role[] = ['counterManager', 'floorSupervisor', 'brandSupervisor'];

  const isSalesPage = location.pathname.startsWith('/sales');
  const isPromotionPage = location.pathname.startsWith('/promotion/') && !location.pathname.endsWith('/new');

  return (
    <div className="min-h-screen bg-slate-50 flex">
      <aside 
        className={`${
          sidebarOpen ? 'w-64' : 'w-16'
        } bg-navy-500 text-white transition-all duration-300 flex flex-col shrink-0`}
      >
        <div className="h-16 flex items-center justify-between px-4 border-b border-navy-600">
          {sidebarOpen && (
            <h1 className="font-serif text-lg font-bold text-amber-400 whitespace-nowrap">
              百货专柜工作面
            </h1>
          )}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="p-2 hover:bg-navy-600 rounded-md transition-colors"
          >
            {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>

        <nav className="flex-1 py-4 space-y-1">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path || 
              (item.path !== '/' && location.pathname.startsWith(item.path));
            return (
              <NavLink
                key={item.path}
                to={item.path}
                className={`flex items-center justify-between px-4 py-3 transition-all duration-200 ${
                  isActive 
                    ? 'bg-navy-600 border-r-4 border-amber-500 text-white' 
                    : 'text-navy-100 hover:bg-navy-600 hover:text-white'
                }`}
              >
                <div className="flex items-center">
                  <Icon size={20} className="shrink-0" />
                  {sidebarOpen && (
                    <span className="ml-3 whitespace-nowrap">{item.label}</span>
                  )}
                </div>
                {sidebarOpen && item.badge && (
                  <span className="bg-amber-500 text-white text-xs px-2 py-0.5 rounded-full">
                    {item.badge}
                  </span>
                )}
              </NavLink>
            );
          })}
        </nav>

        {sidebarOpen && (
          <div className="p-4 border-t border-navy-600">
            <div className="flex items-center gap-2 mb-3">
              <Users size={16} className="text-navy-200" />
              <span className="text-sm text-navy-200">当前角色</span>
            </div>
            <div className="space-y-2">
              {roles.map((role) => (
                <button
                  key={role}
                  onClick={() => setCurrentRole(role)}
                  className={`w-full text-left px-3 py-2 rounded-md text-sm transition-all duration-200 ${
                    currentRole === role
                      ? 'bg-amber-500 text-white font-medium'
                      : 'text-navy-100 hover:bg-navy-600'
                  }`}
                >
                  {ROLE_LABELS[role]}
                </button>
              ))}
            </div>
            <p className="mt-3 text-xs text-navy-300">
              切换角色可体验不同环节的处理流程
            </p>
          </div>
        )}
      </aside>

      <main className="flex-1 flex flex-col min-w-0">
        <header className="h-16 bg-white border-b border-slate-200 px-6 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-4">
            <h2 className="font-serif text-xl font-semibold text-navy-500">
              {getPageTitle(location.pathname)}
            </h2>
            {(isPromotionPage || isSalesPage) && (
              <div className="flex items-center gap-1 pl-4 border-l border-slate-200">
                {isPromotionPage && (
                  <button
                    onClick={() => {
                      const id = location.pathname.split('/').pop();
                      if (id) navigate(`/sales/${id}`);
                    }}
                    className="btn btn-secondary text-sm gap-1.5 py-1.5 px-3"
                  >
                    <ShoppingBag size={14} />
                    销售核对
                    {salesReviewCount > 0 && (
                      <span className="bg-purple-500 text-white text-[10px] px-1.5 py-0.5 rounded-full ml-1">
                        {salesReviewCount}
                      </span>
                    )}
                  </button>
                )}
                {isSalesPage && (
                  <button
                    onClick={() => {
                      const parts = location.pathname.split('/');
                      const id = parts.length > 2 ? parts[2] : null;
                      if (id) navigate(`/promotion/${id}`);
                      else navigate('/');
                    }}
                    className="btn btn-secondary text-sm gap-1.5 py-1.5 px-3"
                  >
                    <RefreshCw size={14} />
                    促销活动
                  </button>
                )}
              </div>
            )}
          </div>
          <div className="flex items-center gap-3">
            {salesReviewCount > 0 && !isSalesPage && (
              <button
                onClick={() => navigate('/sales')}
                className="text-sm text-purple-600 hover:text-purple-700 font-medium flex items-center gap-1"
              >
                <ShoppingBag size={14} />
                {salesReviewCount} 单待核对
              </button>
            )}
            <span className={`badge role-badge-${currentRole}`}>
              {ROLE_LABELS[currentRole]}视角
            </span>
          </div>
        </header>

        <div className="flex-1 overflow-auto p-6">
          {children}
        </div>
      </main>
    </div>
  );
}

function getPageTitle(path: string): string {
  if (path === '/') return '工作台';
  if (path.startsWith('/promotion/new')) return '新建促销活动';
  if (path.startsWith('/promotion/')) return '促销活动处理';
  if (path.startsWith('/sales')) return '销售核对回看';
  if (path === '/io') return '导入导出';
  return '百货专柜工作面';
}

// src/lib/components/Layout.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import {
		Home,
		Clock,
		CalendarClock,
		Users,
		LogOut,
		UserRound,
		Menu,
		X
	} from '@lucide/svelte';
	import type { User } from '$lib/types';

	let { user, children } = $props<{ user: User; children: () => void }>();

	let sidebarOpen = $state(false);

	const roleNames: Record<string, string> = {
		consultant: '课程顾问',
		teacher: '任课老师',
		admin: '校区主管'
	};

	const menuItems = [
		{ id: 'home', name: '首页', icon: Home, path: '/', roles: ['consultant', 'teacher', 'admin'] },
		{
			id: 'consumption',
			name: '课包消耗',
			icon: Clock,
			path: '/consumption',
			roles: ['consultant', 'teacher', 'admin']
		},
		{
			id: 'makeup',
			name: '补课安排',
			icon: CalendarClock,
			path: '/makeup',
			roles: ['consultant', 'teacher', 'admin']
		},
		{
			id: 'students',
			name: '学生档案',
			icon: Users,
			path: '/students',
			roles: ['consultant', 'teacher', 'admin']
		}
	];

	const filteredMenuItems = $derived(menuItems.filter((item) => item.roles.includes(user.role)));

	async function handleLogout() {
		await fetch('/logout', { method: 'POST' });
		await goto('/login');
	}

	async function handleSwitchRole() {
		await fetch('/logout', { method: 'POST' });
		await goto('/login');
	}

	function toggleSidebar() {
		sidebarOpen = !sidebarOpen;
	}
</script>

<div class="min-h-screen bg-gray-50 flex" style="font-family: 'Noto Sans SC', sans-serif;">
	<aside
		class="fixed inset-y-0 left-0 z-50 w-64 bg-teal-700 transform transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static lg:inset-0 {sidebarOpen
			? 'translate-x-0'
			: '-translate-x-full'}"
	>
		<div class="flex flex-col h-full">
			<div class="flex items-center justify-between h-16 px-6 border-b border-teal-600">
				<h1 class="text-xl font-bold text-white">艺术培训机构</h1>
				<button
					onclick={toggleSidebar}
					class="lg:hidden p-2 rounded-lg text-teal-200 hover:bg-teal-600 transition-colors"
				>
					<X size={20} />
				</button>
			</div>

			<nav class="flex-1 px-3 py-4 space-y-1">
				{#each filteredMenuItems as item (item.id)}
					<a
						href={item.path}
						class="flex items-center px-4 py-3 rounded-lg text-teal-100 hover:bg-teal-600 hover:text-white transition-colors duration-200 group {$page.url
							.pathname === item.path
							? 'bg-teal-600 text-white'
							: ''}"
					>
						<svelte:component
							this={item.icon}
							size={20}
							class="mr-3 flex-shrink-0 {$page.url.pathname === item.path ? 'text-white' : 'text-teal-300 group-hover:text-white'}"
						/>
						<span class="font-medium">{item.name}</span>
					</a>
				{/each}
			</nav>

			<div class="p-4 border-t border-teal-600">
				<div class="flex items-center">
					<div class="w-10 h-10 rounded-full bg-teal-500 flex items-center justify-center text-white font-semibold">
						{user.name.charAt(0).toUpperCase()}
					</div>
					<div class="ml-3 flex-1">
						<p class="text-sm font-medium text-white">{user.name}</p>
						<p class="text-xs text-teal-300">{roleNames[user.role]}</p>
					</div>
				</div>
			</div>
		</div>
	</aside>

	{#if sidebarOpen}
		<button
			type="button"
			class="fixed inset-0 z-40 bg-black/50 lg:hidden"
			onclick={() => (sidebarOpen = false)}
			aria-label="关闭侧边栏"
		></button>
	{/if}

	<div class="flex-1 flex flex-col min-w-0">
		<header class="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 lg:px-6 shadow-sm">
			<div class="flex items-center">
				<button
					onclick={toggleSidebar}
					class="lg:hidden p-2 rounded-lg text-gray-600 hover:bg-gray-100 transition-colors mr-4"
				>
					<Menu size={20} />
				</button>
				<h2 class="text-lg font-semibold text-gray-800">
					{filteredMenuItems.find((item) => item.path === $page.url.pathname)?.name || '首页'}
				</h2>
			</div>

			<div class="flex items-center space-x-3">
				<div class="hidden sm:flex items-center px-3 py-1.5 bg-teal-50 rounded-lg">
					<span class="text-sm text-teal-700 font-medium">{roleNames[user.role]}</span>
				</div>

				<div class="relative group">
					<button
						onclick={handleSwitchRole}
						class="flex items-center px-3 py-2 text-sm text-gray-600 hover:text-teal-700 hover:bg-teal-50 rounded-lg transition-colors"
					>
						<UserRound size={18} class="mr-1.5" />
						<span class="hidden sm:inline">切换角色</span>
					</button>
				</div>

				<button
					onclick={handleLogout}
					class="flex items-center px-3 py-2 text-sm text-gray-600 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
				>
					<LogOut size={18} class="mr-1.5" />
					<span class="hidden sm:inline">退出登录</span>
				</button>
			</div>
		</header>

		<main class="flex-1 p-4 lg:p-6 overflow-auto">
			{@render children()}
		</main>
	</div>
</div>
