// pages/inspections/reports.vue
<script setup lang="ts">
import { useInspectionStore } from '~/stores/inspection'
import { ref, computed } from 'vue'

const store = useInspectionStore()

const searchQuery = ref('')
const dateFilter = ref('all')

const filteredReports = computed(() => {
  return store.dailyReports.filter(report => {
    const matchesSearch = !searchQuery.value || 
      report.storeName.toLowerCase().includes(searchQuery.value.toLowerCase())
    
    return matchesSearch
  })
})

const formatTime = (time: string) => {
  return new Date(time).toLocaleDateString('zh-CN')
}
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <header class="bg-white shadow-sm border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-3">
            <button
              @click="navigateTo('/')"
              class="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              ←
            </button>
            <div>
              <h1 class="text-xl font-bold text-gray-900">门店日报</h1>
              <p class="text-sm text-gray-500">门店经营数据日报汇总</p>
            </div>
          </div>
          <a href="/" class="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors">
            返回首页
          </a>
        </div>
      </div>
    </header>

    <nav class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex space-x-1">
          <a href="/" class="px-4 py-3 text-gray-600 hover:text-gray-900 hover:bg-gray-50 transition-colors">首页</a>
          <a href="/inspections" class="px-4 py-3 text-gray-600 hover:text-gray-900 hover:bg-gray-50 transition-colors">巡店检查</a>
          <a href="/rectification" class="px-4 py-3 text-gray-600 hover:text-gray-900 hover:bg-gray-50 transition-colors">整改复盘</a>
          <a href="/workspace" class="px-4 py-3 text-gray-600 hover:text-gray-900 hover:bg-gray-50 transition-colors">工作台</a>
        </div>
      </div>
    </nav>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
        <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div class="flex-1">
            <div class="relative">
              <span class="absolute inset-y-0 left-3 flex items-center text-gray-400">🔍</span>
              <input
                v-model="searchQuery"
                type="text"
                placeholder="搜索门店名称..."
                class="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div
          v-for="report in filteredReports"
          :key="report.id"
          class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"
        >
          <div class="flex items-center justify-between mb-4">
            <h3 class="font-semibold text-gray-900">{{ report.storeName }}</h3>
            <span class="text-sm text-gray-400">{{ report.reportDate }}</span>
          </div>
          <div class="grid grid-cols-3 gap-2 text-center mb-4">
            <div>
              <p class="text-xl font-bold text-gray-900">¥{{ report.sales.toLocaleString() }}</p>
              <p class="text-xs text-gray-400">销售额</p>
            </div>
            <div>
              <p class="text-xl font-bold text-gray-900">{{ report.customers }}</p>
              <p class="text-xs text-gray-400">顾客数</p>
            </div>
            <div>
              <p class="text-xl font-bold text-gray-900">¥{{ report.avgCheck.toFixed(1) }}</p>
              <p class="text-xs text-gray-400">客单价</p>
            </div>
          </div>
          <div v-if="report.notes" class="p-3 bg-gray-50 rounded-lg">
            <p class="text-sm text-gray-600">{{ report.notes }}</p>
          </div>
          <p class="text-xs text-gray-400 mt-3">上报时间: {{ formatTime(report.createdAt) }}</p>
        </div>
      </div>

      <div v-if="filteredReports.length === 0" class="text-center py-12">
        <span class="text-4xl">📊</span>
        <p class="mt-4 text-gray-500">没有找到日报记录</p>
      </div>
    </main>
  </div>
</template>

// src/pages/inspector/Reports.tsx
import { useState } from 'react';
import { Search } from 'lucide-react';
import { AppLayout } from '../../components/layout/AppLayout';
import { Card, CardContent } from '../../components/common/Card';
import { StatusBadge } from '../../components/common/StatusBadge';
import { EmptyState } from '../../components/common/EmptyState';
import { useData } from '../../contexts/DataContext';
import { INSPECTOR_SIDEBAR } from '../../utils/constants';
import { formatDate } from '../../utils/helpers';

export function InspectorReports() {
  const { vehicles, reports } = useData();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  const filteredReports = reports.filter(report => {
    const vehicle = vehicles.find(v => v.id === report.vehicleId);
    const matchesSearch = vehicle?.plateNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         vehicle?.ownerName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || report.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const getVehicle = (vehicleId: string) => {
    return vehicles.find(v => v.id === vehicleId);
  };

  const statusCounts = {
    all: reports.length,
    '待审核': reports.filter(r => r.status === '待审核').length,
    '已通过': reports.filter(r => r.status === '已通过').length,
    '已驳回': reports.filter(r => r.status === '已驳回').length,
  };

  return (
    <AppLayout role="inspector" sidebarItems={INSPECTOR_SIDEBAR}>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">我的报告</h1>
          <p className="text-gray-500 mt-1">查看已提交的检测报告</p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="搜索车牌号或车主姓名..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-inspector"
                />
              </div>
            </div>
            
            <div className="flex gap-2">
              {Object.entries(statusCounts).map(([status, count]) => (
                <button
                  key={status}
                  onClick={() => setStatusFilter(status)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    statusFilter === status
                      ? 'bg-inspector text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {status === 'all' ? '全部' : status} ({count})
                </button>
              ))}
            </div>
          </div>
        </div>

        {filteredReports.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredReports.map((report) => {
              const vehicle = getVehicle(report.vehicleId);
              return (
                <Card key={report.id}>
                  <CardContent>
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="text-xl font-bold text-gray-900">
                          {vehicle?.plateNumber}
                        </h3>
                        <p className="text-sm text-gray-500 mt-1">
                          {vehicle?.ownerName}
                        </p>
                      </div>
                      <StatusBadge status={report.status} />
                    </div>

                    <div className="space-y-2 mb-4">
                      <div className="flex items-center text-sm">
                        <span className="text-gray-500 w-20">检测结论：</span>
                        <span className={`font-medium ${
                          report.conclusion === '合格' ? 'text-green-600' : 'text-red-600'
                        }`}>
                          {report.conclusion}
                        </span>
                      </div>
                      <div className="flex items-center text-sm">
                        <span className="text-gray-500 w-20">提交时间：</span>
                        <span className="text-gray-900">{formatDate(report.submittedAt || '')}</span>
                      </div>
                      {report.auditorName && (
                        <div className="flex items-center text-sm">
                          <span className="text-gray-500 w-20">审核员：</span>
                          <span className="text-gray-900">{report.auditorName}</span>
                        </div>
                      )}
                    </div>

                    {report.status === '已驳回' && report.rejectReason && (
                      <div className="p-3 bg-red-50 rounded-lg mb-4">
                        <p className="text-sm text-red-600">
                          <span className="font-medium">驳回原因：</span>
                          {report.rejectReason}
                        </p>
                      </div>
                    )}

                    {report.status === '已通过' && report.auditedAt && (
                      <div className="p-3 bg-green-50 rounded-lg">
                        <p className="text-sm text-green-600">
                          审核通过 · {formatDate(report.auditedAt)}
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        ) : (
          <EmptyState
            title="暂无报告"
            description={searchTerm ? '没有找到匹配的报告' : '还没有提交任何检测报告'}
          />
        )}
      </div>
    </AppLayout>
  );
}
