// labor-dispatch/client/src/views/Login.vue
<template>
  <div class="login-container">
    <el-card class="login-card">
      <template #header>
        <div class="card-header">
          <h2>人力派遣公司管理系统</h2>
          <p>用工需求与候选人匹配</p>
        </div>
      </template>

      <el-form :model="loginForm" :rules="rules" ref="formRef" label-width="80px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="loginForm.username" placeholder="请输入用户名" />
        </el-form-item>

        <el-form-item label="密码" prop="password">
          <el-input
            v-model="loginForm.password"
            type="password"
            placeholder="请输入密码"
            @keyup.enter="handleLogin"
          />
        </el-form-item>

        <el-form-item>
          <el-button type="primary" @click="handleLogin" :loading="loading" style="width: 100%">
            登录
          </el-button>
        </el-form-item>

        <div class="demo-account">
          <p>演示账号：</p>
          <p>管理员：admin / admin123</p>
          <p>一线人员：user / user123</p>
        </div>
      </el-form>
    </el-card>
  </div>
</template>

<script>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import api from '../api'

export default {
  name: 'Login',
  setup() {
    const router = useRouter()
    const formRef = ref(null)
    const loading = ref(false)

    const loginForm = reactive({
      username: '',
      password: ''
    })

    const rules = {
      username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
      password: [{ required: true, message: '请输入密码', trigger: 'blur' }]
    }

    const handleLogin = async () => {
      try {
        await formRef.value.validate()
        loading.value = true

        const response = await api.auth.login(loginForm)

        localStorage.setItem('token', response.token)
        localStorage.setItem('user', JSON.stringify(response.user))

        ElMessage.success('登录成功')

        router.push('/dashboard')
      } catch (error) {
        ElMessage.error(error.response?.data?.error || '登录失败')
      } finally {
        loading.value = false
      }
    }

    return {
      loginForm,
      rules,
      formRef,
      loading,
      handleLogin
    }
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-card {
  width: 450px;
}

.card-header {
  text-align: center;
}

.card-header h2 {
  margin-bottom: 10px;
  color: #333;
}

.card-header p {
  color: #666;
  font-size: 14px;
}

.demo-account {
  margin-top: 20px;
  padding: 15px;
  background: #f5f7fa;
  border-radius: 4px;
  font-size: 13px;
  color: #666;
}

.demo-account p {
  margin: 5px 0;
}
</style>

// src/routes/login/+page.svelte
<script lang="ts">
	let username = '';
	let password = '';
	let error = '';
	let loading = false;

	async function login() {
		if (!username || !password) {
			error = '请输入用户名和密码';
			return;
		}

		loading = true;
		error = '';

		try {
			const res = await fetch('/api/auth/login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ username, password })
			});

			const data = await res.json();

			if (data.success) {
				window.location.href = '/';
			} else {
				error = data.error || '登录失败';
			}
		} catch (e) {
			error = '网络错误，请稍后重试';
		}

		loading = false;
	}
</script>

<div class="login-container">
	<div class="login-card">
		<h1>税务风险跟踪系统</h1>
		<p class="subtitle">风险提示与后续跟踪管理平台</p>

		<form on:submit|preventDefault={login}>
			<div class="form-group">
				<label class="label" for="username">用户名（工号）</label>
				<input
					id="username"
					class="input"
					type="text"
					placeholder="例如：TA001、PM001、CF001"
					bind:value={username}
					disabled={loading}
				/>
			</div>

			<div class="form-group">
				<label class="label" for="password">密码</label>
				<input
					id="password"
					class="input"
					type="password"
					placeholder="password123"
					bind:value={password}
					disabled={loading}
				/>
			</div>

			{#if error}
				<div class="error-message">{error}</div>
			{/if}

			<button class="btn btn-primary btn-block" type="submit" disabled={loading}>
				{#if loading}
					登录中...
				{:else}
					登录
				{/if}
			</button>
		</form>

		<div class="demo-users">
			<p class="demo-title">测试账号：</p>
			<div class="demo-list">
				<div class="demo-item">
					<strong>TA001</strong> - 张税务（税务顾问）
				</div>
				<div class="demo-item">
					<strong>PM001</strong> - 李经理（项目经理）
				</div>
				<div class="demo-item">
					<strong>CF001</strong> - 王财务（客户财务）
				</div>
			</div>
			<p class="demo-note">密码均为：password123</p>
		</div>
	</div>
</div>

<style>
	.login-container {
		display: flex;
		justify-content: center;
		align-items: center;
		min-height: 100vh;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
	}

	.login-card {
		background: var(--card-bg);
		border-radius: 0.75rem;
		box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
		padding: 2.5rem;
		width: 100%;
		max-width: 400px;
	}

	h1 {
		font-size: 1.75rem;
		font-weight: 700;
		color: var(--text-primary);
		margin: 0 0 0.5rem 0;
		text-align: center;
	}

	.subtitle {
		font-size: 0.875rem;
		color: var(--text-secondary);
		text-align: center;
		margin: 0 0 2rem 0;
	}

	.form-group {
		margin-bottom: 1.5rem;
	}

	.error-message {
		background: #fee2e2;
		color: #991b1b;
		padding: 0.75rem;
		border-radius: 0.375rem;
		font-size: 0.875rem;
		margin-bottom: 1rem;
	}

	.btn-block {
		width: 100%;
		padding: 0.75rem;
		font-size: 1rem;
	}

	.demo-users {
		margin-top: 2rem;
		padding-top: 1.5rem;
		border-top: 1px solid var(--border-color);
	}

	.demo-title {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--text-primary);
		margin: 0 0 0.75rem 0;
	}

	.demo-list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.demo-item {
		font-size: 0.875rem;
		color: var(--text-secondary);
	}

	.demo-item strong {
		color: var(--primary-color);
	}

	.demo-note {
		font-size: 0.75rem;
		color: var(--text-secondary);
		margin: 0.75rem 0 0 0;
		font-style: italic;
	}
</style>
